package com.example.murotalquran.Ayat;

public class AyatAnNaziat {

    public static String[] IdAnNaziat = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
            "1023",
            "1024",
            "1025",
            "1026",
            "1027",
            "1028",
            "1029",
            "1030",
            "1031",
            "1032",
            "1033",
            "1034",
            "1035",
            "1036",
            "1037",
            "1038",
            "1039",
            "1040",
    };

    public static String[] NoAnNaziat = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
    };

    public static String[] ArabAnNaziat = {"وَالنّٰزِعٰتِ غَرْقًاۙ",
            "وَّالنّٰشِطٰتِ نَشْطًاِۙۙ",
            "وَّالسّٰبِحٰتِ سَبْحًاَۙۗ",
            "فَالسّٰبِقٰتِ سَبْقًاۙ",
            "فَالْمُدَبِّرٰتِ اَمْرًاَۘ",
            "يَوْمَ تَرْجُفُ الرَّاجِفَةُۙۙ",
            "تَتْبَعُهَا الرَّادِفَةُ ۗۖ",
            "قُلُوْبٌ يَّوْمَىِٕذٍ وَّاجِفَةٌۙۙ",
            "اَبْصَارُهَا خَاشِعَةٌ ۘۙ",
            "يَقُوْلُوْنَ ءَاِنَّا لَمَرْدُوْدُوْنَ فِى الْحَافِرَةِۗۙ",
            "ءَاِذَا كُنَّا عِظَامًا نَّخِرَةً ۗ",
            "قَالُوْا تِلْكَ اِذًا كَرَّةٌ خَاسِرَةٌ ۘۙ",
            "فَاِنَّمَا هِيَ زَجْرَةٌ وَّاحِدَةٌۙۖ",
            "فَاِذَا هُمْ بِالسَّاهِرَةِۗۙ",
            "هَلْ اَتٰىكَ حَدِيْثُ مُوْسٰىۘۙ",
            "اِذْ نَادٰىهُ رَبُّهٗ بِالْوَادِ الْمُقَدَّسِ طُوًىۚ",
            "اِذْهَبْ اِلٰى فِرْعَوْنَ اِنَّهٗ طَغٰىۖۙ",
            "فَقُلْ هَلْ لَّكَ اِلٰٓى اَنْ تَزَكّٰىۙۙ",
            "وَاَهْدِيَكَ اِلٰى رَبِّكَ فَتَخْشٰىۚ",
            "فَاَرٰىهُ الْاٰيَةَ الْكُبْرٰىۖ",
            "فَكَذَّبَ وَعَصٰىۖۙ",
            "ثُمَّ اَدْبَرَ يَسْعٰىۖۙ",
            "فَحَشَرَ فَنَادٰىۖۚ",
            "فَقَالَ اَنَا۠ رَبُّكُمُ الْاَعْلٰىۖ",
            "فَاَخَذَهُ اللّٰهُ نَكَالَ الْاٰخِرَةِ وَالْاُوْلٰىۗۙ",
            "اِنَّ فِيْ ذٰلِكَ لَعِبْرَةً لِّمَنْ يَّخْشٰى ۗۗ",
            "ءَاَنْتُمْ اَشَدُّ خَلْقًا اَمِ السَّمَاۤءُ ۚ بَنٰىهَاۗۙ",
            "رَفَعَ سَمْكَهَا فَسَوّٰىهَاۙۗ",
            "وَاَغْطَشَ لَيْلَهَا وَاَخْرَجَ ضُحٰىهَاۖۙ",
            "وَالْاَرْضَ بَعْدَ ذٰلِكَ دَحٰىهَاۗ",
            "اَخْرَجَ مِنْهَا مَاۤءَهَا وَمَرْعٰىهَاۖۙ",
            "وَالْجِبَالَ اَرْسٰىهَاۙ",
            "مَتَاعًا لَّكُمْ وَلِاَنْعَامِكُمْۗۙ",
            "فَاِذَا جَاۤءَتِ الطَّاۤمَّةُ الْكُبْرٰىۖ",
            "يَوْمَ يَتَذَكَّرُ الْاِنْسَانُ مَا سَعٰىۙ",
            "وَبُرِّزَتِ الْجَحِيْمُ لِمَنْ يَّرٰىۙ",
            "فَاَمَّا مَنْ طَغٰىۖۚ",
            "وَاٰثَرَ الْحَيٰوةَ الدُّنْيَاۙ",
            "فَاِنَّ الْجَحِيْمَ هِيَ الْمَأْوٰىۗ",
            "وَاَمَّا مَنْ خَافَ مَقَامَ رَبِّهٖ وَنَهَى النَّفْسَ عَنِ الْهَوٰىۙ",
            "فَاِنَّ الْجَنَّةَ هِيَ الْمَأْوٰىۗ",
            "يَسْـَٔلُوْنَكَ عَنِ السَّاعَةِ اَيَّانَ مُرْسٰىهَاۗ",
            "فِيْمَ اَنْتَ مِنْ ذِكْرٰىهَاۗ",
            "اِلٰى رَبِّكَ مُنْتَهٰىهَاۗ",
            "اِنَّمَآ اَنْتَ مُنْذِرُ مَنْ يَّخْشٰىهَاۗ",
            "كَاَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوْٓا اِلَّا عَشِيَّةً اَوْ ضُحٰىهَا",
    };

    public static String[] LatinAnNaziat = {"wan-nāzi'āti garqā",
            "wan-nāsyiṭāti nasyṭā",
            "was-sābiḥāti sab-ḥā",
            "fas-sābiqāti sabqā",
            "fal-mudabbirāti amrā",
            "yauma tarjufur-rājifah",
            "tatba'uhar-rādifah",
            "qulụbuy yauma`iżiw wājifah",
            "abṣāruhā khāsyi'ah",
            "yaqụlụna a innā lamardụdụna fil-ḥāfirah",
            "a iżā kunnā 'iẓāman nakhirah",
            "qālụ tilka iżang karratun khāsirah",
            "fa innamā hiya zajratuw wāḥidah",
            "fa iżā hum bis-sāhirah",
            "hal atāka ḥadīṡu mụsā",
            "iż nādāhu rabbuhụ bil-wādil-muqaddasi ṭuwā",
            "iż-hab ilā fir'auna innahụ ṭagā",
            "fa qul hal laka ilā an tazakkā",
            "wa ahdiyaka ilā rabbika fa takhsyā",
            "fa arāhul-āyatal-kubrā",
            "fa każżaba wa 'aṣā",
            "ṡumma adbara yas'ā",
            "fa ḥasyara fa nādā",
            "fa qāla ana rabbukumul-a'lā",
            "fa akhażahullāhu nakālal-ākhirati wal-ụlā",
            "inna fī żālika la'ibratal limay yakhsyā",
            "a antum asyaddu khalqan amis-samā`, banāhā",
            "rafa'a samkahā fa sawwāhā",
            "wa agṭasya lailahā wa akhraja ḍuḥāhā",
            "wal-arḍa ba'da żālika daḥāhā",
            "akhraja min-hā mā`ahā wa mar'āhā",
            "wal-jibāla arsāhā",
            "matā'al lakum wa li`an'āmikum",
            "fa iżā jā`atiṭ-ṭāmmatul-kubrā",
            "yauma yatażakkarul-insānu mā sa'ā",
            "wa burrizatil-jaḥīmu limay yarā",
            "fa ammā man ṭagā",
            "wa āṡaral-ḥayātad-dun-yā",
            "fa innal-jaḥīma hiyal-ma`wā",
            "wa ammā man khāfa maqāma rabbihī wa nahan-nafsa 'anil-hawā",
            "fa innal-jannata hiyal-ma`wā",
            "yas`alụnaka 'anis-sā'ati ayyāna mursāhā",
            "fīma anta min żikrāhā",
            "ilā rabbika muntahāhā",
            "innamā anta munżiru may yakhsyāhā",
            "ka`annahum yauma yaraunahā lam yalbaṡū illā 'asyiyyatan au ḍuḥāhā",
    };

    public static String[] ArtiAnNaziat = {"Demi (malaikat) yang mencabut (nyawa) dengan keras.",
            "Demi (malaikat) yang mencabut (nyawa) dengan lemah lembut.",
            "Demi (malaikat) yang turun dari langit dengan cepat,",
            "dan (malaikat) yang mendahului dengan kencang,",
            "dan (malaikat) yang mengatur urusan (dunia).",
            "(Sungguh, kamu akan dibangkitkan) pada hari ketika tiupan pertama mengguncangkan alam,",
            "(tiupan pertama) itu diiringi oleh tiupan kedua.",
            "Hati manusia pada waktu itu merasa sangat takut,",
            "pandangannya tunduk.",
            "(Orang-orang kafir) berkata, “Apakah kita benar-benar akan dikembalikan kepada kehidupan yang semula?",
            "Apakah (akan dibangkitkan juga) apabila kita telah menjadi tulang belulang yang hancur?”",
            "Mereka berkata, “Kalau demikian, itu adalah suatu pengembalian yang merugikan.”",
            "Maka pengembalian itu hanyalah dengan sekali tiupan saja.",
            "Maka seketika itu mereka hidup kembali di bumi (yang baru).",
            "Sudahkah sampai kepadamu (Muhammad) kisah Musa?",
            "Ketika Tuhan memanggilnya (Musa) di lembah suci yaitu Lembah Tuwa;",
            "pergilah engkau kepada Fir‘aun! Sesungguhnya dia telah melampaui batas,",
            "Maka katakanlah (kepada Fir‘aun), “Adakah keinginanmu untuk membersihkan diri (dari kesesatan),",
            "dan engkau akan kupimpin ke jalan Tuhanmu agar engkau takut kepada-Nya?”",
            "Lalu (Musa) memperlihatkan kepadanya mukjizat yang besar.",
            "Tetapi dia (Fir‘aun) mendustakan dan mendurhakai.",
            "Kemudian dia berpaling seraya berusaha menantang (Musa).",
            "Kemudian dia mengumpulkan (pembesar-pembesarnya) lalu berseru (memanggil kaumnya).",
            "(Seraya) berkata, “Akulah tuhanmu yang paling tinggi.”",
            "Maka Allah menghukumnya dengan azab di akhirat dan siksaan di dunia.",
            "Sungguh, pada yang demikian itu terdapat pelajaran bagi orang yang takut (kepada Allah).",
            "Apakah penciptaan kamu yang lebih hebat ataukah langit yang telah dibangun-Nya?",
            "Dia telah meninggikan bangunannya lalu menyempurnakannya,",
            "dan Dia menjadikan malamnya (gelap gulita), dan menjadikan siangnya (terang benderang).",
            "Dan setelah itu bumi Dia hamparkan.",
            "Darinya Dia pancarkan mata air, dan (ditumbuhkan) tumbuh-tumbuhannya.",
            "Dan gunung-gunung Dia pancangkan dengan teguh.",
            "(Semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu.",
            "Maka apabila malapetaka besar (hari Kiamat) telah datang,",
            "yaitu pada hari (ketika) manusia teringat akan apa yang telah dikerjakannya,",
            "dan neraka diperlihatkan dengan jelas kepada setiap orang yang melihat.",
            "Maka adapun orang yang melampaui batas,",
            "dan lebih mengutamakan kehidupan dunia,",
            "maka sungguh, nerakalah tempat tinggalnya.",
            "Dan adapun orang-orang yang takut kepada kebesaran Tuhannya dan menahan diri dari (keinginan) hawa nafsunya,",
            "maka sungguh, surgalah tempat tinggal(nya).",
            "Mereka (orang-orang kafir) bertanya kepadamu (Muhammad) tentang hari Kiamat, “Kapankah terjadinya?”",
            "Untuk apa engkau perlu menyebutkannya (waktunya)?",
            "Kepada Tuhanmulah (dikembalikan) kesudahannya (ketentuan waktunya).",
            "Engkau (Muhammad) hanyalah pemberi peringatan bagi siapa yang takut kepadanya (hari Kiamat).",
            "Pada hari ketika mereka melihat hari Kiamat itu (karena suasananya hebat), mereka merasa seakan-akan hanya (sebentar saja) tinggal (di dunia) pada waktu sore atau pagi hari.",
    };
}
