package com.example.murotalquran.Ayat;

public class AyatAnNaba {

    public static String[] IdAnNaba = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
            "1023",
            "1024",
            "1025",
            "1026",
            "1027",
            "1028",
            "1029",
            "1030",
            "1031",
            "1032",
            "1033",
            "1034",
            "1035",
            "1036",
            "1037",
            "1038",
            "1039",
            "1040",
    };

    public static String[] NoAnNaba = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
    };

    public static String[] ArabAnNaba = {"عَمَّ يَتَسَاۤءَلُوْنَۚ",
            "عَنِ النَّبَاِ الْعَظِيْمِۙ",
            "الَّذِيْ هُمْ فِيْهِ مُخْتَلِفُوْنَۗ",
            "كَلَّا سَيَعْلَمُوْنَۙ",
            "ثُمَّ كَلَّا سَيَعْلَمُوْنَ",
            "اَلَمْ نَجْعَلِ الْاَرْضَ مِهٰدًاۙ",
            "وَّالْجِبَالَ اَوْتَادًاۖ",
            "وَّخَلَقْنٰكُمْ اَزْوَاجًاۙ",
            "وَّجَعَلْنَا نَوْمَكُمْ سُبَاتًاۙ",
            "وَّجَعَلْنَا الَّيْلَ لِبَاسًاۙ",
            "وَّجَعَلْنَا النَّهَارَ مَعَاشًاۚ",
            "وَبَنَيْنَا فَوْقَكُمْ سَبْعًا شِدَادًاۙ",
            "وَّجَعَلْنَا سِرَاجًا وَّهَّاجًاۖ",
            "وَّاَنْزَلْنَا مِنَ الْمُعْصِرٰتِ مَاۤءً ثَجَّاجًاۙ",
            "لِّنُخْرِجَ بِهٖ حَبًّا وَّنَبَاتًاۙ",
            "وَّجَنّٰتٍ اَلْفَافًاۗ",
            "اِنَّ يَوْمَ الْفَصْلِ كَانَ مِيْقَاتًاۙ",
            "يَّوْمَ يُنْفَخُ فِى الصُّوْرِ فَتَأْتُوْنَ اَفْوَاجًاۙ",
            "وَّفُتِحَتِ السَّمَاۤءُ فَكَانَتْ اَبْوَابًاۙ",
            "وَّسُيِّرَتِ الْجِبَالُ فَكَانَتْ سَرَابًاۗ",
            "اِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًاۙ",
            "لِّلطّٰغِيْنَ مَاٰبًاۙ",
            "لّٰبِثِيْنَ فِيْهَآ اَحْقَابًاۚ",
            "لَا يَذُوْقُوْنَ فِيْهَا بَرْدًا وَّلَا شَرَابًاۙ",
            "اِلَّا حَمِيْمًا وَّغَسَّاقًاۙ",
            "جَزَاۤءً وِّفَاقًاۗ",
            "اِنَّهُمْ كَانُوْا لَا يَرْجُوْنَ حِسَابًاۙ",
            "وَّكَذَّبُوْا بِاٰيٰتِنَا كِذَّابًاۗ",
            "وَكُلَّ شَيْءٍ اَحْصَيْنٰهُ كِتٰبًاۙ",
            "فَذُوْقُوْا فَلَنْ نَّزِيْدَكُمْ اِلَّا عَذَابًا",
            "اِنَّ لِلْمُتَّقِيْنَ مَفَازًاۙ",
            "حَدَاۤىِٕقَ وَاَعْنَابًاۙ",
            "وَّكَوَاعِبَ اَتْرَابًاۙ",
            "وَّكَأْسًا دِهَاقًاۗ",
            "لَا يَسْمَعُوْنَ فِيْهَا لَغْوًا وَّلَا كِذَّابًا",
            "جَزَاۤءً مِّنْ رَّبِّكَ عَطَاۤءً حِسَابًاۙ",
            "رَّبِّ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَا الرَّحْمٰنِ لَا يَمْلِكُوْنَ مِنْهُ خِطَابًاۚ",
            "يَوْمَ يَقُوْمُ الرُّوْحُ وَالْمَلٰۤىِٕكَةُ صَفًّاۙ لَّا يَتَكَلَّمُوْنَ اِلَّا مَنْ اَذِنَ لَهُ الرَّحْمٰنُ وَقَالَ صَوَابًا",
            "ذٰلِكَ الْيَوْمُ الْحَقُّۚ فَمَنْ شَاۤءَ اتَّخَذَ اِلٰى رَبِّهٖ مَاٰبًا",
            "اِنَّآ اَنْذَرْنٰكُمْ عَذَابًا قَرِيْبًا ەۙ يَّوْمَ يَنْظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُوْلُ الْكٰفِرُ يٰلَيْتَنِيْ كُنْتُ تُرَابًا",
    };

    public static String[] LatinAnNaba = {"'amma yatasā`alụn",
            "'anin-naba`il-'aẓīm",
            "allażī hum fīhi mukhtalifụn",
            "kallā saya'lamụn",
            "ṡumma kallā saya'lamụn",
            "alam naj'alil-arḍa mihādā",
            "wal-jibāla autādā",
            "wa khalaqnākum azwājā",
            "wa ja'alnā naumakum subātā",
            "wa ja'alnal-laila libāsā",
            "wa ja'alnan-nahāra ma'āsyā",
            "wa banainā fauqakum sab'an syidādā",
            "wa ja'alnā sirājaw wahhājā",
            "wa anzalnā minal-mu'ṣirāti mā`an ṡajjājā",
            "linukhrija bihī ḥabbaw wa nabātā",
            "wa jannātin alfāfā",
            "inna yaumal-faṣli kāna mīqātā",
            "yauma yunfakhu fiṣ-ṣụri fa ta`tụna afwājā",
            "wa futiḥatis-samā`u fa kānat abwābā",
            "wa suyyiratil-jibālu fa kānat sarābā",
            "inna jahannama kānat mirṣādā",
            "liṭ-ṭāgīna ma`ābā",
            "lābiṡīna fīhā aḥqābā",
            "lā yażụqụna fīhā bardaw wa lā syarābā",
            "illā ḥamīmaw wa gassāqā",
            "jazā`aw wifāqā",
            "innahum kānụ lā yarjụna ḥisābā",
            "wa każżabụ bi`āyātinā kiżżābā",
            "wa kulla syai`in aḥṣaināhu kitābā",
            "fa żụqụ fa lan nazīdakum illā 'ażābā",
            "inna lil-muttaqīna mafāzā",
            "ḥadā`iqa wa a'nābā",
            "wa kawā'iba atrābā",
            "wa ka`san dihāqā",
            "lā yasma'ụna fīhā lagwaw wa lā kiżżābā",
            "jazā`am mir rabbika 'aṭā`an ḥisābā",
            "rabbis-samāwāti wal-arḍi wa mā bainahumar-raḥmāni lā yamlikụna min-hu khiṭābā",
            "yauma yaqụmur-rụḥu wal-malā`ikatu ṣaffal lā yatakallamụna illā man ażina lahur-raḥmānu wa qāla ṣawābā",
            "żālikal-yaumul-ḥaqq, fa man syā`attakhaża ilā rabbihī ma`ābā",
            "innā anżarnākum 'ażābang qarībay yauma yanẓurul-mar`u mā qaddamat yadāhu wa yaqụlul-kāfiru yā laitanī kuntu turābā",
    };

    public static String[] ArtiAnNaba = {"Tentang apakah mereka saling bertanya-tanya?",
            "Tentang berita yang besar (hari kebangkitan),",
            "yang dalam hal itu mereka berselisih.",
            "Tidak! Kelak mereka akan mengetahui,",
            "sekali lagi tidak! Kelak mereka akan mengetahui.",
            "Bukankah Kami telah menjadikan bumi sebagai hamparan,",
            "dan gunung-gunung sebagai pasak?",
            "Dan Kami menciptakan kamu berpasang-pasangan,",
            "dan Kami menjadikan tidurmu untuk istirahat,",
            "dan Kami menjadikan malam sebagai pakaian,",
            "dan Kami menjadikan siang untuk mencari penghidupan,",
            "dan Kami membangun di atas kamu tujuh (langit) yang kokoh,",
            "dan Kami menjadikan pelita yang terang-benderang (matahari),",
            "dan Kami turunkan dari awan, air hujan yang tercurah dengan hebatnya,",
            "untuk Kami tumbuhkan dengan air itu biji-bijian dan tanam-tanaman,",
            "dan kebun-kebun yang rindang.",
            "Sungguh, hari keputusan adalah suatu waktu yang telah ditetapkan,",
            "(yaitu) pada hari (ketika) sangkakala ditiup, lalu kamu datang berbondong-bondong,",
            "dan langit pun dibukalah, maka terdapatlah beberapa pintu,",
            "dan gunung-gunung pun dijalankan sehingga menjadi fatamorgana.",
            "Sungguh, (neraka) Jahanam itu (sebagai) tempat mengintai (bagi penjaga yang mengawasi isi neraka),",
            "menjadi tempat kembali bagi orang-orang yang melampaui batas.",
            "Mereka tinggal di sana dalam masa yang lama,",
            "mereka tidak merasakan kesejukan di dalamnya dan tidak (pula mendapat) minuman,",
            "selain air yang mendidih dan nanah,",
            "sebagai pembalasan yang setimpal.",
            "Sesungguhnya dahulu mereka tidak pernah mengharapkan perhitungan.",
            "Dan mereka benar-benar mendustakan ayat-ayat Kami.",
            "Dan segala sesuatu telah Kami catat dalam suatu Kitab (buku catatan amalan manusia).",
            "Maka karena itu rasakanlah! Maka tidak ada yang akan Kami tambahkan kepadamu selain azab.",
            "Sungguh, orang-orang yang bertakwa mendapat kemenangan,",
            "(yaitu) kebun-kebun dan buah anggur,",
            "dan gadis-gadis montok yang sebaya,",
            "dan gelas-gelas yang penuh (berisi minuman).",
            "Di sana mereka tidak mendengar percakapan yang sia-sia maupun (perkataan) dusta.",
            "Sebagai balasan dan pemberian yang cukup banyak dari Tuhanmu,",
            "Tuhan (yang memelihara) langit dan bumi dan apa yang ada di antara keduanya; Yang Maha Pengasih, mereka tidak mampu berbicara dengan Dia.",
            "Pada hari, ketika ruh dan para malaikat berdiri bersaf-saf, mereka tidak berkata-kata, kecuali siapa yang telah diberi izin kepadanya oleh Tuhan Yang Maha Pengasih dan dia hanya mengatakan yang benar.",
            "Itulah hari yang pasti terjadi. Maka barang siapa menghendaki, niscaya dia menempuh jalan kembali kepada Tuhannya.",
            "Sesungguhnya Kami telah memperingatkan kepadamu (orang kafir) azab yang dekat, pada hari manusia melihat apa yang telah diperbuat oleh kedua tangannya; dan orang kafir berkata, “Alangkah baiknya seandainya dahulu aku jadi tanah.”",
    };
}
