package com.example.murotalquran.Ayat;

public class AyatAlAlaq {

    public static String [] IdAlAlaq = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019"
    };

    public static String []  NoAlAlaq = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19"
    };

    public static String [] ArabAlAlaq = {"اِقْرَأْ بِاسْمِ رَبِّكَ الَّذِيْ خَلَقَۚ",
            "خَلَقَ الْاِنْسَانَ مِنْ عَلَقٍۚ",
            "اِقْرَأْ وَرَبُّكَ الْاَكْرَمُۙ",
            "الَّذِيْ عَلَّمَ بِالْقَلَمِۙ",
            "عَلَّمَ الْاِنْسَانَ مَا لَمْ يَعْلَمْۗ",
            "كَلَّآ اِنَّ الْاِنْسَانَ لَيَطْغٰىٓ ۙ",
            "اَنْ رَّاٰهُ اسْتَغْنٰىۗ",
            "اِنَّ اِلٰى رَبِّكَ الرُّجْعٰىۗ",
            "اَرَاَيْتَ الَّذِيْ يَنْهٰىۙ",
            "عَبْدًا اِذَا صَلّٰىۗ",
            "اَرَاَيْتَ اِنْ كَانَ عَلَى الْهُدٰىٓۙ",
            "اَوْ اَمَرَ بِالتَّقْوٰىۗ",
            "اَرَاَيْتَ اِنْ كَذَّبَ وَتَوَلّٰىۗ",
            "اَلَمْ يَعْلَمْ بِاَنَّ اللّٰهَ يَرٰىۗ",
            "كَلَّا لَىِٕنْ لَّمْ يَنْتَهِ ەۙ لَنَسْفَعًاۢ بِالنَّاصِيَةِۙ",
            "نَاصِيَةٍ كَاذِبَةٍ خَاطِئَةٍۚ",
            "فَلْيَدْعُ نَادِيَهٗۙ",
            "سَنَدْعُ الزَّبَانِيَةَۙ",
            "كَلَّاۗ لَا تُطِعْهُ وَاسْجُدْ وَاقْتَرِبْ ۩"
    };

    public static String [] LatinAlAlaq = {"iqra` bismi rabbikallażī khalaq",
            "khalaqal-insāna min 'alaq",
            "iqra` wa rabbukal-akram",
            "allażī 'allama bil-qalam",
            "'allamal-insāna mā lam ya'lam",
            "kallā innal-insāna layaṭgā",
            "ar ra`āhustagnā",
            "inna ilā rabbikar-ruj'ā",
            "a ra`aitallażī yan-hā",
            "'abdan iżā ṣallā",
            "a ra`aita ing kāna 'alal-hudā",
            "au amara bit-taqwā",
            "a ra`aita ing każżaba wa tawallā",
            "a lam ya'lam bi`annallāha yarā",
            "kallā la`il lam yantahi lanasfa'am bin-nāṣiyah",
            "nāṣiyating kāżibatin khāṭi`ah",
            "falyad'u nādiyah",
            "sanad'uz-zabāniyah",
            "kallā, lā tuṭi'hu wasjud waqtarib"
    };

    public static String [] ArtiAlAlaq = {"Bacalah dengan (menyebut) nama Tuhanmu yang menciptakan,",
            "Dia telah menciptakan manusia dari segumpal darah.",
            "Bacalah, dan Tuhanmulah Yang Mahamulia,",
            "Yang mengajar (manusia) dengan pena.",
            "Dia mengajarkan manusia apa yang tidak diketahuinya.",
            "Sekali-kali tidak! Sungguh, manusia itu benar-benar melampaui batas,",
            "apabila melihat dirinya serba cukup.",
            "Sungguh, hanya kepada Tuhanmulah tempat kembali(mu).",
            "Bagaimana pendapatmu tentang orang yang melarang?",
            "seorang hamba ketika dia melaksanakan salat,",
            "bagaimana pendapatmu jika dia (yang dilarang salat itu) berada di atas kebenaran (petunjuk),",
            "atau dia menyuruh bertakwa (kepada Allah)?",
            "Bagaimana pendapatmu jika dia (yang melarang) itu mendustakan dan berpaling?",
            "Tidakkah dia mengetahui bahwa sesungguhnya Allah melihat (segala perbuatannya)?",
            "Sekali-kali tidak! Sungguh, jika dia tidak berhenti (berbuat demikian) niscaya Kami tarik ubun-ubunnya, (ke dalam neraka),",
            "yaitu) ubun-ubun orang yang mendustakan dan durhaka.",
            "Maka biarlah dia memanggil golongannya (untuk menolongnya),",
            "Kelak Kami akan memanggil Malaikat Zabaniyah, (penyiksa orang-orang yang berdosa),",
            "sekali-kali tidak! Janganlah kamu patuh kepadanya; dan sujudlah serta dekatkanlah (dirimu kepada Allah)."
    };

}
