package com.example.murotalquran.Ayat;

public class AyatAlLail {

    public static String [] IdAlLail = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021"
    };

    public static String [] NoAlLail = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21"
    };

    public static String [] ArabAlLail = {"وَالَّيْلِ اِذَا يَغْشٰىۙ",
            "وَالنَّهَارِ اِذَا تَجَلّٰىۙ",
            "وَمَا خَلَقَ الذَّكَرَ وَالْاُنْثٰىٓ ۙ",
            "اِنَّ سَعْيَكُمْ لَشَتّٰىۗ",
            "فَاَمَّا مَنْ اَعْطٰى وَاتَّقٰىۙ",
            "وَصَدَّقَ بِالْحُسْنٰىۙ",
            "فَسَنُيَسِّرُهٗ لِلْيُسْرٰىۗ",
            "وَاَمَّا مَنْۢ بَخِلَ وَاسْتَغْنٰىۙ",
            "وَكَذَّبَ بِالْحُسْنٰىۙ",
            "فَسَنُيَسِّرُهٗ لِلْعُسْرٰىۗ",
            "وَمَا يُغْنِيْ عَنْهُ مَالُهٗٓ اِذَا تَرَدّٰىٓۙ",
            "اِنَّ عَلَيْنَا لَلْهُدٰىۖ",
            "وَاِنَّ لَنَا لَلْاٰخِرَةَ وَالْاُوْلٰىۗ",
            "فَاَنْذَرْتُكُمْ نَارًا تَلَظّٰىۚ",
            "لَا يَصْلٰىهَآ اِلَّا الْاَشْقَىۙ",
            "الَّذِيْ كَذَّبَ وَتَوَلّٰىۗ",
            "وَسَيُجَنَّبُهَا الْاَتْقَىۙ",
            "الَّذِيْ يُؤْتِيْ مَالَهٗ يَتَزَكّٰىۚ",
            "وَمَا لِاَحَدٍ عِنْدَهٗ مِنْ نِّعْمَةٍ تُجْزٰىٓۙ",
            "اِلَّا ابْتِغَاۤءَ وَجْهِ رَبِّهِ الْاَعْلٰىۚ",
            "وَلَسَوْفَ يَرْضٰى"
    };

    public static String [] LatinAlLail = {"wal-laili iżā yagsyā",
            "wan-nahāri iżā tajallā",
            "wa mā khalaqaż-żakara wal-unṡā",
            "inna sa'yakum lasyattā",
            "fa ammā man a'ṭā wattaqā",
            "wa ṣaddaqa bil-ḥusnā",
            "fa sanuyassiruhụ lil-yusrā",
            "wa ammā mam bakhila wastagnā",
            "wa każżaba bil-ḥusnā",
            "fa sanuyassiruhụ lil-'usrā",
            "wa mā yugnī 'an-hu māluhū iżā taraddā",
            "inna 'alainā lal-hudā",
            "wa inna lanā lal-ākhirata wal-ụlā",
            "fa anżartukum nāran talaẓẓā",
            "lā yaṣlāhā illal-asyqā",
            "allażī każżaba wa tawallā",
            "wa sayujannabuhal-atqā",
            "allażī yu`tī mālahụ yatazakkā",
            "wa mā li`aḥadin 'indahụ min ni'matin tujzā",
            "illabtigā`a waj-hi rabbihil-a'lā",
            "wa lasaufa yarḍā"
    };

    public static String [] ArtiAlLail = {"Demi malam apabila menutupi (cahaya siang),",
            "demi siang apabila terang benderang,",
            "demi penciptaan laki-laki dan perempuan,",
            "sungguh, usahamu memang beraneka macam.",
            "Maka barangsiapa memberikan (hartanya di jalan Allah) dan bertakwa,",
            "dan membenarkan (adanya pahala) yang terbaik (surga),",
            "maka akan Kami mudahkan baginya jalan menuju kemudahan (kebahagiaan),",
            "dan adapun orang yang kikir dan merasa dirinya cukup (tidak perlu pertolongan Allah),",
            "serta mendustakan (pahala) yang terbaik,",
            "maka akan Kami mudahkan baginya jalan menuju kesukaran (kesengsaraan),",
            "dan hartanya tidak bermanfaat baginya apabila dia telah binasa.",
            "Sesungguhnya Kamilah yang memberi petunjuk,",
            "dan sesungguhnya milik Kamilah akhirat dan dunia itu.",
            "Maka Aku memperingatkan kamu dengan neraka yang menyala-nyala,",
            "yang hanya dimasuki oleh orang yang paling celaka,",
            "yang mendustakan (kebenaran) dan berpaling (dari iman).",
            "Dan akan dijauhkan darinya (neraka) orang yang paling bertakwa,",
            "yang menginfakkan hartanya (di jalan Allah) untuk membersihkan (dirinya),",
            "dan tidak ada seorang pun memberikan suatu nikmat padanya yang harus dibalasnya,",
            "tetapi (dia memberikan itu semata-mata) karena mencari keridaan Tuhannya Yang Mahatinggi.",
            "Dan niscaya kelak dia akan mendapat kesenangan (yang sempurna)."
    };

}
