package com.example.murotalquran.Ayat;

public class AyatAlFajr {

    public static String [] IdAlFajr = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
            "1023",
            "1024",
            "1025",
            "1026",
            "1027",
            "1028",
            "1029",
            "1030"
    };

    public static String [] NoAlFajr = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30"
    };

    public static String [] ArabAlFajr = {"وَالْفَجْرِۙ",
            "وَلَيَالٍ عَشْرٍۙ",
            "وَّالشَّفْعِ وَالْوَتْرِۙ",
            "وَالَّيْلِ اِذَا يَسْرِۚ",
            "هَلْ فِيْ ذٰلِكَ قَسَمٌ لِّذِيْ حِجْرٍۗ",
            "اَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِعَادٍۖ",
            "اِرَمَ ذَاتِ الْعِمَادِۖ",
            "الَّتِيْ لَمْ يُخْلَقْ مِثْلُهَا فِى الْبِلَادِۖ",
            "وَثَمُوْدَ الَّذِيْنَ جَابُوا الصَّخْرَ بِالْوَادِۖ",
            "وَفِرْعَوْنَ ذِى الْاَوْتَادِۖ",
            "الَّذِيْنَ طَغَوْا فِى الْبِلَادِۖ",
            "فَاَكْثَرُوْا فِيْهَا الْفَسَادَۖ",
            "فَصَبَّ عَلَيْهِمْ رَبُّكَ سَوْطَ عَذَابٍۖ",
            "اِنَّ رَبَّكَ لَبِالْمِرْصَادِۗ",
            "فَاَمَّا الْاِنْسَانُ اِذَا مَا ابْتَلٰىهُ رَبُّهٗ فَاَكْرَمَهٗ وَنَعَّمَهٗۙ فَيَقُوْلُ رَبِّيْٓ اَكْرَمَنِۗ",
            "وَاَمَّآ اِذَا مَا ابْتَلٰىهُ فَقَدَرَ عَلَيْهِ رِزْقَهٗ ەۙ فَيَقُوْلُ رَبِّيْٓ اَهَانَنِۚ",
            "كَلَّا بَلْ لَّا تُكْرِمُوْنَ الْيَتِيْمَۙ",
            "وَلَا تَحٰۤضُّوْنَ عَلٰى طَعَامِ الْمِسْكِيْنِۙ",
            "وَتَأْكُلُوْنَ التُّرَاثَ اَكْلًا لَّمًّاۙ",
            "وَّتُحِبُّوْنَ الْمَالَ حُبًّا جَمًّاۗ",
            "كَلَّآ اِذَا دُكَّتِ الْاَرْضُ دَكًّا دَكًّاۙ",
            "وَّجَآءَ رَبُّكَ وَالْمَلَكُ صَفًّا صَفًّاۚ",
            "وَجِايْۤءَ يَوْمَىِٕذٍۢ بِجَهَنَّمَۙ يَوْمَىِٕذٍ يَّتَذَكَّرُ الْاِنْسَانُ وَاَنّٰى لَهُ الذِّكْرٰىۗ",
            "يَقُوْلُ يٰلَيْتَنِيْ قَدَّمْتُ لِحَيَاتِيْۚ",
            "فَيَوْمَىِٕذٍ لَّا يُعَذِّبُ عَذَابَهٗٓ اَحَدٌ ۙ",
            "وَّلَا يُوْثِقُ وَثَاقَهٗٓ اَحَدٌ ۗ",
            "يٰٓاَيَّتُهَا النَّفْسُ الْمُطْمَىِٕنَّةُۙ",
            "ارْجِعِيْٓ اِلٰى رَبِّكِ رَاضِيَةً مَّرْضِيَّةً ۚ",
            "فَادْخُلِيْ فِيْ عِبٰدِيْۙ",
            "وَادْخُلِيْ جَنَّتِي"
    };

    public static String [] LatinAlFajr = {"wal-fajr",
            "wa layālin 'asyr",
            "wasy-syaf'i wal-watr",
            "wal-laili iżā yasr",
            "hal fī żālika qasamul liżī ḥijr",
            "a lam tara kaifa fa'ala rabbuka bi'ād",
            "irama żātil-'imād",
            "allatī lam yukhlaq miṡluhā fil-bilād",
            "wa ṡamụdallażīna jābuṣ-ṣakhra bil-wād",
            "wa fir'auna żil-autād",
            "allażīna ṭagau fil-bilād",
            "fa akṡarụ fīhal-fasād",
            "fa ṣabba 'alaihim rabbuka sauṭa 'ażāb",
            "inna rabbaka labil-mirṣād",
            "fa ammal-insānu iżā mabtalāhu rabbuhụ fa akramahụ wa na''amahụ fa yaqụlu rabbī akraman",
            "wa ammā iżā mabtalāhu fa qadara 'alaihi rizqahụ fa yaqụlu rabbī ahānan",
            "kallā bal lā tukrimụnal-yatīm",
            "wa lā tahāḍḍụna 'alā ṭa'āmil-miskīn",
            "wa ta`kulụnat-turāṡa aklal lammā",
            "wa tuḥibbụnal-māla ḥubban jammā",
            "kallā iżā dukkatil-arḍu dakkan dakkā",
            "wa jā`a rabbuka wal-malaku ṣaffan ṣaffā",
            "wa jī`a yauma`iżim bijahannama yauma`iżiy yatażakkarul-insānu wa annā lahuż-żikrā",
            "yaqụlu yā laitanī qaddamtu liḥayātī",
            "fa yauma`iżil lā yu'ażżibu 'ażābahū aḥad",
            "wa lā yụṡiqu waṡāqahū aḥad",
            "yā ayyatuhan-nafsul-muṭma`innah",
            "irji'ī ilā rabbiki rāḍiyatam marḍiyyah",
            "fadkhulī fī 'ibādī",
            "wadkhulī jannatī"
    };

    public static String [] ArtiAlFajr = {"Demi fajar,",
            "demi malam yang sepuluh,",
            "demi yang genap dan yang ganjil,",
            "demi malam apabila berlalu.",
            "Adakah pada yang demikian itu terdapat sumpah (yang dapat diterima) bagi orang-orang yang berakal?",
            "Tidakkah engkau (Muhammad) memperhatikan bagaimana Tuhanmu berbuat terhadap (kaum) ‘Ad?",
            "(yaitu) penduduk Iram (ibukota kaum ‘Ad) yang mempunyai bangunan-bangunan yang tinggi,",
            "yang belum pernah dibangun (suatu kota) seperti itu di negeri-negeri lain,",
            "dan (terhadap) kaum samud yang memotong batu-batu besar di lembah,",
            "dan (terhadap) Fir‘aun yang mempunyai pasak-pasak (bangunan yang besar),",
            "yang berbuat sewenang-wenang dalam negeri,",
            "lalu mereka banyak berbuat kerusakan dalam negeri itu,",
            "karena itu Tuhanmu menimpakan cemeti azab kepada mereka,",
            "sungguh, Tuhanmu benar-benar mengawasi.",
            "Maka adapun manusia, apabila Tuhan mengujinya lalu memuliakannya dan memberinya kesenangan, maka dia berkata, “Tuhanku telah memuliakanku.”",
            "Namun apabila Tuhan mengujinya lalu membatasi rezekinya, maka dia berkata, “Tuhanku telah menghinaku.”",
            "Sekali-kali tidak! Bahkan kamu tidak memuliakan anak yatim,",
            "dan kamu tidak saling mengajak memberi makan orang miskin,",
            "sedangkan kamu memakan harta warisan dengan cara mencampurbaurkan (yang halal dan yang haram),",
            "dan kamu mencintai harta dengan kecintaan yang berlebihan.",
            "Sekali-kali tidak! Apabila bumi diguncangkan berturut-turut (berbenturan),",
            "dan datanglah Tuhanmu; dan malaikat berbaris-baris,",
            "dan pada hari itu diperlihatkan neraka Jahanam; pada hari itu sadarlah manusia, tetapi tidak berguna lagi baginya kesadaran itu.",
            "Dia berkata, “Alangkah baiknya sekiranya dahulu aku mengerjakan (kebajikan) untuk hidupku ini.”",
            "Maka pada hari itu tidak ada seorang pun yang mengazab seperti azab-Nya (yang adil),",
            "dan tidak ada seorang pun yang mengikat seperti ikatan-Nya.",
            "Wahai jiwa yang tenang!",
            "Kembalilah kepada Tuhanmu dengan hati yang rida dan diridai-Nya.",
            "Maka masuklah ke dalam golongan hamba-hamba-Ku,",
            "dan masuklah ke dalam surga-Ku."
    };

}
