package com.example.murotalquran.Ayat;

public class AyatAlGhasyiyah {

    public static String [] IdAlGhasyiyah = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
            "1023",
            "1024",
            "1025",
            "1026"
    };

    public static String [] NoAlGhasyiyah = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26"
    };

    public static String [] ArabAlGhasyiyah = {"هَلْ اَتٰىكَ حَدِيْثُ الْغَاشِيَةِۗ",
            "وُجُوْهٌ يَّوْمَىِٕذٍ خَاشِعَةٌ ۙ",
            "عَامِلَةٌ نَّاصِبَةٌ ۙ",
            "تَصْلٰى نَارًا حَامِيَةً ۙ",
            "تُسْقٰى مِنْ عَيْنٍ اٰنِيَةٍ ۗ",
            "لَيْسَ لَهُمْ طَعَامٌ اِلَّا مِنْ ضَرِيْعٍۙ",
            "لَّا يُسْمِنُ وَلَا يُغْنِيْ مِنْ جُوْعٍۗ",
            "وُجُوْهٌ يَّوْمَىِٕذٍ نَّاعِمَةٌ ۙ",
            "لِّسَعْيِهَا رَاضِيَةٌ ۙ",
            "فِيْ جَنَّةٍ عَالِيَةٍۙ",
            "لَّا تَسْمَعُ فِيْهَا لَاغِيَةً ۗ",
            "فِيْهَا عَيْنٌ جَارِيَةٌ ۘ",
            "فِيْهَا سُرُرٌ مَّرْفُوْعَةٌ ۙ",
            "وَّاَكْوَابٌ مَّوْضُوْعَةٌ ۙ",
            "وَّنَمَارِقُ مَصْفُوْفَةٌ ۙ",
            "وَّزَرَابِيُّ مَبْثُوْثَةٌ ۗ",
            "اَفَلَا يَنْظُرُوْنَ اِلَى الْاِبِلِ كَيْفَ خُلِقَتْۗ",
            "وَاِلَى السَّمَاۤءِ كَيْفَ رُفِعَتْۗ",
            "وَاِلَى الْجِبَالِ كَيْفَ نُصِبَتْۗ",
            "وَاِلَى الْاَرْضِ كَيْفَ سُطِحَتْۗ",
            "فَذَكِّرْۗ اِنَّمَآ اَنْتَ مُذَكِّرٌۙ",
            "لَّسْتَ عَلَيْهِمْ بِمُصَيْطِرٍۙ",
            "اِلَّا مَنْ تَوَلّٰى وَكَفَرَۙ",
            "فَيُعَذِّبُهُ اللّٰهُ الْعَذَابَ الْاَكْبَرَۗ",
            "اِنَّ اِلَيْنَآ اِيَابَهُمْ",
            "ثُمَّ اِنَّ عَلَيْنَا حِسَابَهُمْ"
    };

    public static String [] LatinAlGhasyiyah = {"hal atāka ḥadīṡul-gāsyiyah",
            "wujụhuy yauma`iżin khāsyi'ah",
            "'āmilatun nāṣibah",
            "taṣlā nāran ḥāmiyah",
            "tusqā min 'ainin āniyah",
            "laisa lahum ṭa'āmun illā min ḍarī'",
            "lā yusminu wa lā yugnī min jụ'",
            "wujụhuy yauma`iżin nā'imah",
            "lisa'yihā rāḍiyah",
            "fī jannatin 'āliyah",
            "lā tasma'u fīhā lāgiyah",
            "fīhā 'ainun jāriyah",
            "fīhā sururum marfụ'ah",
            "wa akwābum mauḍụ'ah",
            "wa namāriqu maṣfụfah",
            "wa zarābiyyu mabṡụṡah",
            "a fa lā yanẓurụna ilal-ibili kaifa khuliqat",
            "wa ilas-samā`i kaifa rufi'at",
            "wa ilal-jibāli kaifa nuṣibat",
            "wa ilal-arḍi kaifa suṭiḥat",
            "fa żakkir, innamā anta mużakkir",
            "lasta 'alaihim bimuṣaiṭir",
            "illā man tawallā wa kafar",
            "fa yu'ażżibuhullāhul-'ażābal-akbar",
            "inna ilainā iyābahum",
            "ṡumma inna 'alainā ḥisābahum"
    };

    public static String [] ArtiAlGhasyiyah = {"Sudahkah sampai kepadamu berita tentang (hari Kiamat)?",
            "Pada hari itu banyak wajah yang tertunduk terhina,",
            "(karena) bekerja keras lagi kepayahan,",
            "mereka memasuki api yang sangat panas (neraka),",
            "diberi minum dari sumber mata air yang sangat panas.",
            "Tidak ada makanan bagi mereka selain dari pohon yang berduri,",
            "yang tidak menggemukkan dan tidak menghilangkan lapar.",
            "Pada hari itu banyak (pula) wajah yang berseri-seri,",
            "merasa senang karena usahanya (sendiri),",
            "(mereka) dalam surga yang tinggi,",
            "di sana (kamu) tidak mendengar perkataan yang tidak berguna.",
            "Di sana ada mata air yang mengalir.",
            "Di sana ada dipan-dipan yang ditinggikan,",
            "dan gelas-gelas yang tersedia (di dekatnya),",
            "dan bantal-bantal sandaran yang tersusun,",
            "dan permadani-permadani yang terhampar.",
            "Maka tidakkah mereka memperhatikan unta, bagaimana diciptakan?",
            "dan langit, bagaimana ditinggikan?",
            "Dan gunung-gunung bagaimana ditegakkan?",
            "Dan bumi bagaimana dihamparkan?",
            "Maka berilah peringatan, karena sesungguhnya engkau (Muhammad) hanyalah pemberi peringatan.",
            "Engkau bukanlah orang yang berkuasa atas mereka,",
            "kecuali (jika ada) orang yang berpaling dan kafir,",
            "maka Allah akan mengazabnya dengan azab yang besar.",
            "Sungguh, kepada Kamilah mereka kembali,",
            "kemudian sesungguhnya (kewajiban) Kamilah membuat perhitungan atas mereka."
    };

}
