package com.example.murotalquran.Ayat;

public class AyatAbasa {

    public static String[] IdAbasa = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
            "1023",
            "1024",
            "1025",
            "1026",
            "1027",
            "1028",
            "1029",
            "1030",
            "1031",
            "1032",
            "1033",
            "1034",
            "1035",
            "1036",
            "1037",
            "1038",
            "1039",
            "1040",
            "1041",
            "1042",
    };

    public static String[] NoAbasa = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
    };

    public static String[] ArabAbasa = {"عَبَسَ وَتَوَلّٰىٓۙ",
            "اَنْ جَاۤءَهُ الْاَعْمٰىِۗۙ",
            "وَمَا يُدْرِيْكَ لَعَلَّهٗ يَزَّكّٰىَٓۙۗ",
            "اَوْ يَذَّكَّرُ فَتَنْفَعَهُ الذِّكْرٰىَۗۙ",
            "اَمَّا مَنِ اسْتَغْنٰىَۙ",
            "فَاَنْتَ لَهٗ تَصَدّٰىۗ",
            "وَمَا عَلَيْكَ اَلَّا يَزَّكّٰىۗۖ",
            "وَاَمَّا مَنْ جَاۤءَكَ يَسْعٰىۙ",
            "وَهُوَ يَخْشٰىۙۙ",
            "فَاَنْتَ عَنْهُ تَلَهّٰىۚۙ",
            "كَلَّآ اِنَّهَا تَذْكِرَةٌ ۚۚ",
            "فَمَنْ شَاۤءَ ذَكَرَهٗ ۘۙ",
            "فِيْ صُحُفٍ مُّكَرَّمَةٍۙۖ",
            "مَّرْفُوْعَةٍ مُّطَهَّرَةٍ ۢ ۙۙ",
            "بِاَيْدِيْ سَفَرَةٍۙۙ",
            "كِرَامٍۢ بَرَرَةٍۗ",
            "قُتِلَ الْاِنْسَانُ مَآ اَكْفَرَهٗۗ",
            "مِنْ اَيِّ شَيْءٍ خَلَقَهٗۗ",
            "مِنْ نُّطْفَةٍۗ خَلَقَهٗ فَقَدَّرَهٗۗۙ",
            "ثُمَّ السَّبِيْلَ يَسَّرَهٗۙۗ",
            "ثُمَّ اَمَاتَهٗ فَاَقْبَرَهٗۙۙ",
            "ثُمَّ اِذَا شَاۤءَ اَنْشَرَهٗۗۙ",
            "كَلَّا لَمَّا يَقْضِ مَآ اَمَرَهٗۗۚ",
            "فَلْيَنْظُرِ الْاِنْسَانُ اِلٰى طَعَامِهٖٓ ۙۙ",
            "اَنَّا صَبَبْنَا الْمَاۤءَ صَبًّاۙۙ",
            "ثُمَّ شَقَقْنَا الْاَرْضَ شَقًّاۙ",
            "فَاَنْۢبَتْنَا فِيْهَا حَبًّاۙۙ",
            "وَّعِنَبًا وَّقَضْبًاۙ",
            "وَّزَيْتُوْنًا وَّنَخْلًاۙۙ",
            "وَّحَدَاۤئِقَ غُلْبًا",
            "وَفَاكِهَةً وَّاَبًّاۙ",
            "مَتَاعًا لَّكُمْ وَلِاَنْعَامِكُمْۗۙ",
            "فَاِذَا جَاۤءَتِ الصَّاۤخَّةُ ۖۙ",
            "يَوْمَ يَفِرُّ الْمَرْءُ مِنْ اَخِيْهِۙ",
            "وَاُمِّهٖ وَاَبِيْهِۙ",
            "وَصَاحِبَتِهٖ وَبَنِيْهِۗۙ",
            "لِكُلِّ امْرِئٍ مِّنْهُمْ يَوْمَىِٕذٍ شَأْنٌ يُّغْنِيْهِۗۚ",
            "وُجُوْهٌ يَّوْمَىِٕذٍ مُّسْفِرَةٌۙ",
            "ضَاحِكَةٌ مُّسْتَبْشِرَةٌ ۚ",
            "وَوُجُوْهٌ يَّوْمَىِٕذٍ عَلَيْهَا غَبَرَةٌۙ",
            "تَرْهَقُهَا قَتَرَةٌ ٌۗۙ",
            "اُولٰۤىِٕكَ هُمُ الْكَفَرَةُ الْفَجَرَةٌُۙ",
    };

    public static String[] LatinAbasa = {"'abasa wa tawallā",
            "an jā`ahul-a'mā",
            "wa mā yudrīka la'allahụ yazzakkā",
            "au yażżakkaru fa tanfa'ahuż-żikrā",
            "ammā manistagnā",
            "fa anta lahụ taṣaddā",
            "wa mā 'alaika allā yazzakkā",
            "wa ammā man jā`aka yas'ā",
            "wa huwa yakhsyā",
            "fa anta 'an-hu talahhā",
            "kallā innahā tażkirah",
            "fa man syā`a żakarah",
            "fī ṣuḥufim mukarramah",
            "marfụ'atim muṭahharah",
            "bi`aidī safarah",
            "kirāmim bararah",
            "qutilal-insānu mā akfarah",
            "min ayyi syai`in khalaqah",
            "min nuṭfah, khalaqahụ fa qaddarah",
            "ṡummas-sabīla yassarah",
            "ṡumma amātahụ fa aqbarah",
            "ṡumma iżā syā`a ansyarah",
            "kallā lammā yaqḍi mā amarah",
            "falyanẓuril-insānu ilā ṭa'āmih",
            "annā ṣababnal-mā`a ṣabbā",
            "ṡumma syaqaqnal-arḍa syaqqā",
            "fa ambatnā fīhā ḥabbā",
            "wa 'inabaw wa qaḍbā",
            "wa zaitụnaw wa nakhlā",
            "wa ḥadā`iqa gulbā",
            "wa fākihataw wa abbā",
            "matā'al lakum wa li`an'āmikum.",
            "fa iżā jā`atiṣ-ṣākhkhah",
            "yauma yafirrul-mar`u min akhīh",
            "wa ummihī wa abīh",
            "wa ṣāḥibatihī wa banīh",
            "likullimri`im min-hum yauma`iżin sya`nuy yugnīh",
            "wujụhuy yauma`iżim musfirah",
            "ḍāḥikatum mustabsyirah",
            "wa wujụhuy yauma`iżin 'alaihā gabarah",
            "tarhaquhā qatarah",
            "ulā`ika humul-kafaratul-fajarah",
    };

    public static String[] ArtiAbasa = {"Dia (Muhammad) berwajah masam dan berpaling,",
            "karena seorang buta telah datang kepadanya (Abdullah bin Ummi Maktum).",
            "Dan tahukah engkau (Muhammad) barangkali dia ingin menyucikan dirinya (dari dosa),",
            "atau dia (ingin) mendapatkan pengajaran, yang memberi manfaat kepadanya?",
            "Adapun orang yang merasa dirinya serba cukup (pembesar-pembesar Quraisy),",
            "maka engkau (Muhammad) memberi perhatian kepadanya,",
            "padahal tidak ada (cela) atasmu kalau dia tidak menyucikan diri (beriman).",
            "Dan adapun orang yang datang kepadamu dengan bersegera (untuk mendapatkan pengajaran),",
            "sedang dia takut (kepada Allah)",
            "engkau (Muhammad) malah mengabaikannya.",
            "Sekali-kali jangan (begitu)! Sungguh, (ajaran-ajaran Allah) itu suatu peringatan,",
            "maka barangsiapa menghendaki, tentulah dia akan memperhatikannya,",
            "di dalam kitab-kitab yang dimuliakan (di sisi Allah),",
            "yang ditinggikan (dan) disucikan,",
            "di tangan para utusan (malaikat),",
            "yang mulia lagi berbakti.",
            "Celakalah manusia! Alangkah kufurnya dia!",
            "Dari apakah Dia (Allah) menciptakannya?",
            "Dari setetes mani, Dia menciptakannya lalu menentukannya.",
            "Kemudian jalannya Dia mudahkan,",
            "kemudian Dia mematikannya lalu menguburkannya,",
            "kemudian jika Dia menghendaki, Dia membangkitkannya kembali.",
            "Sekali-kali jangan (begitu)! Dia (manusia) itu belum melaksanakan apa yang Dia (Allah) perintahkan kepadanya.",
            "Maka hendaklah manusia itu memperhatikan makanannya.",
            "Kamilah yang telah mencurahkan air melimpah (dari langit).",
            "kemudian Kami belah bumi dengan sebaik-baiknya",
            "lalu di sana Kami tumbuhkan biji-bijian,",
            "dan anggur dan sayur-sayuran,",
            "dan zaitun dan pohon kurma,",
            "dan kebun-kebun (yang) rindang,",
            "dan buah-buahan serta rerumputan.",
            "(Semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu.",
            "Maka apabila datang suara yang memekakkan (tiupan sangkakala yang kedua),",
            "pada hari itu manusia lari dari saudaranya,",
            "dan dari ibu dan bapaknya,",
            "dan dari istri dan anak-anaknya.",
            "Setiap orang dari mereka pada hari itu mempunyai urusan yang menyibukkannya.",
            "Pada hari itu ada wajah-wajah yang berseri-seri,",
            "tertawa dan gembira ria,”",
            "dan pada hari itu ada (pula) wajah-wajah yang tertutup debu (suram),",
            "tertutup oleh kegelapan (ditimpa kehinaan dan kesusahan).",
            "Mereka itulah orang-orang kafir yang durhaka.",
    };
}
