package com.example.murotalquran.Ayat;

public class AyatAlInfitar {

    public static String [] IdAlInfitar = {"1001",
        "1002",
        "1003",
        "1004",
        "1005",
        "1006",
        "1007",
        "1008",
        "1009",
        "1010",
        "1011",
        "1012",
        "1013",
        "1014",
        "1015",
        "1016",
        "1017",
        "1018",
        "1019"
    };

    public static String [] NoAlInfitar = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19"
    };

    public static String [] ArabAlInfitar = {"اِذَا السَّمَاۤءُ انْفَطَرَتْۙ",
            "وَاِذَا الْكَوَاكِبُ انْتَثَرَتْۙ",
            "وَاِذَا الْبِحَارُ فُجِّرَتْۙ",
            "وَاِذَا الْقُبُوْرُ بُعْثِرَتْ",
            "عَلِمَتْ نَفْسٌ مَّا قَدَّمَتْ وَاَخَّرَتْۗ",
            "يٰٓاَيُّهَا الْاِنْسَانُ مَا غَرَّكَ بِرَبِّكَ الْكَرِيْمِۙ",
            "الَّذِيْ خَلَقَكَ فَسَوّٰىكَ فَعَدَلَكَۙ",
            "فِيْٓ اَيِّ صُوْرَةٍ مَّا شَاۤءَ رَكَّبَكَۗ",
            "كَلَّا بَلْ تُكَذِّبُوْنَ بِالدِّيْنِۙ",
            "وَاِنَّ عَلَيْكُمْ لَحٰفِظِيْنَۙ",
            "كِرَامًا كَاتِبِيْنَۙ",
            "يَعْلَمُوْنَ مَا تَفْعَلُوْنَ",
            "اِنَّ الْاَبْرَارَ لَفِيْ نَعِيْمٍۙ",
            "وَّاِنَّ الْفُجَّارَ لَفِيْ جَحِيْمٍ",
            "يَصْلَوْنَهَا يَوْمَ الدِّيْنِ",
            "وَمَا هُمْ عَنْهَا بِغَاۤىِٕبِيْنَۗ",
            "وَمَآ اَدْرٰىكَ مَا يَوْمُ الدِّيْنِۙ",
            "ثُمَّ مَآ اَدْرٰىكَ مَا يَوْمُ الدِّيْنِۗ",
            "يَوْمَ لَا تَمْلِكُ نَفْسٌ لِّنَفْسٍ شَيْـًٔا ۗوَالْاَمْرُ يَوْمَىِٕذٍ لِّلّٰهِ"
    };

    public static String [] LatinAlInfitar = {"iżas-samā`unfaṭarat",
            "wa iżal-kawākibuntaṡarat",
            "wa iżal-biḥāru fujjirat",
            "wa iżal-qubụru bu'ṡirat",
            "'alimat nafsum mā qaddamat wa akhkharat",
            "yā ayyuhal-insānu mā garraka birabbikal-karīm",
            "allażī khalaqaka fa sawwāka fa 'adalak",
            "fī ayyi ṣụratim mā syā`a rakkabak",
            "kallā bal tukażżibụna bid-dīn",
            "wa inna 'alaikum laḥāfiẓīn",
            "kirāmang kātibīn",
            "ya'lamụna mā taf'alụn",
            "innal-abrāra lafī na'īm",
            "wa innal-fujjāra lafī jaḥīm",
            "yaṣlaunahā yaumad-dīn",
            "wa mā hum 'an-hā bigā`ibīn",
            "wa mā adrāka mā yaumud-dīn",
            "ṡumma mā adrāka mā yaumud-dīn",
            "yauma lā tamliku nafsul linafsin syai`ā, wal-amru yauma`iżil lillāh"
    };

    public static String [] ArtiAlInfitar = {"Apabila langit terbelah,",
            "dan apabila bintang-bintang jatuh berserakan,",
            "dan apabila lautan dijadikan meluap,",
            "dan apabila kuburan-kuburan dibongkar,",
            "(maka) setiap jiwa akan mengetahui apa yang telah dikerjakan dan yang dilalaikan(nya).",
            "Wahai manusia! Apakah yang telah memperdayakan kamu (berbuat durhaka) terhadap Tuhanmu Yang Mahamulia,",
            "yang telah menciptakanmu lalu menyempurnakan kejadianmu dan menjadikan (susunan tubuh)mu seimbang,",
            "dalam bentuk apa saja yang dikehendaki, Dia menyusun tubuhmu.",
            "Sekali-kali jangan begitu! Bahkan kamu mendustakan hari pembalasan.",
            "Dan sesungguhnya bagi kamu ada (malaikat-malaikat) yang mengawasi (pekerjaanmu),",
            "yang mulia (di sisi Allah) dan yang mencatat (amal perbuatanmu),",
            "mereka mengetahui apa yang kamu kerjakan.",
            "Sesungguhnya orang-orang yang berbakti benar-benar berada dalam (surga yang penuh) kenikmatan,",
            "dan sesungguhnya orang-orang yang durhaka benar-benar berada dalam neraka.",
            "Mereka masuk ke dalamnya pada hari pembalasan.",
            "Dan mereka tidak mungkin keluar dari neraka itu.",
            "Dan tahukah kamu apakah hari pembalasan itu?",
            "Sekali lagi, tahukah kamu apakah hari pembalasan itu?",
            "(Yaitu) pada hari (ketika) seseorang sama sekali tidak berdaya (menolong) orang lain. Dan segala urusan pada hari itu dalam kekuasaan Allah."
    };

}
