package com.example.murotalquran.Ayat;

public class AyatAlBuruj {

    public static String [] IdAlBuruj = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
    };

    public static String [] NoAlBuruj = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
    };

    public static String [] ArabAlBuruj = {"وَالسَّمَاۤءِ ذَاتِ الْبُرُوْجِۙ",
            "وَالْيَوْمِ الْمَوْعُوْدِۙ",
            "وَشَاهِدٍ وَّمَشْهُوْدٍۗ",
            "قُتِلَ اَصْحٰبُ الْاُخْدُوْدِۙ",
            "النَّارِ ذَاتِ الْوَقُوْدِۙ",
            "اِذْ هُمْ عَلَيْهَا قُعُوْدٌۙ",
            "وَّهُمْ عَلٰى مَا يَفْعَلُوْنَ بِالْمُؤْمِنِيْنَ شُهُوْدٌ ۗ",
            "وَمَا نَقَمُوْا مِنْهُمْ اِلَّآ اَنْ يُّؤْمِنُوْا بِاللّٰهِ الْعَزِيْزِ الْحَمِيْدِۙ",
            "الَّذِيْ لَهٗ مُلْكُ السَّمٰوٰتِ وَالْاَرْضِ ۗوَاللّٰهُ عَلٰى كُلِّ شَيْءٍ شَهِيْدٌ ۗ",
            "اِنَّ الَّذِيْنَ فَتَنُوا الْمُؤْمِنِيْنَ وَالْمُؤْمِنٰتِ ثُمَّ لَمْ يَتُوْبُوْا فَلَهُمْ عَذَابُ جَهَنَّمَ وَلَهُمْ عَذَابُ الْحَرِيْقِۗ",
            "اِنَّ الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ لَهُمْ جَنّٰتٌ تَجْرِيْ مِنْ تَحْتِهَا الْاَنْهٰرُ ەۗ ذٰلِكَ الْفَوْزُ الْكَبِيْرُۗ",
            "اِنَّ بَطْشَ رَبِّكَ لَشَدِيْدٌ ۗ",
            "اِنَّهٗ هُوَ يُبْدِئُ وَيُعِيْدُۚ",
            "وَهُوَ الْغَفُوْرُ الْوَدُوْدُۙ",
            "ذُو الْعَرْشِ الْمَجِيْدُۙ",
            "فَعَّالٌ لِّمَا يُرِيْدُۗ",
            "هَلْ اَتٰىكَ حَدِيْثُ الْجُنُوْدِۙ",
            "فِرْعَوْنَ وَثَمُوْدَۗ",
            "بَلِ الَّذِيْنَ كَفَرُوْا فِيْ تَكْذِيْبٍۙ",
            "وَّاللّٰهُ مِنْ وَّرَاۤىِٕهِمْ مُّحِيْطٌۚ",
            "بَلْ هُوَ قُرْاٰنٌ مَّجِيْدٌۙ",
            "فِيْ لَوْحٍ مَّحْفُوْظٍ",
    };

    public static String [] LatinAlBuruj = {"was-samā`i żātil-burụj",
            "wal-yaumil-mau'ụd",
            "wa syāhidiw wa masy-hụd",
            "qutila aṣ-ḥābul-ukhdụd",
            "an-nāri żātil-waqụd",
            "iż hum 'alaihā qu'ụd",
            "wa hum 'alā mā yaf'alụna bil-mu`minīna syuhụd",
            "wa mā naqamụ min-hum illā ay yu`minụ billāhil-'azīzil-ḥamīd",
            "allażī lahụ mulkus-samāwāti wal-arḍ, wallāhu 'alā kulli syai`in syahīd",
            "innallażīna fatanul-mu`minīna wal-mu`mināti ṡumma lam yatụbụ fa lahum 'ażābu jahannama wa lahum 'ażābul-ḥarīq",
            "innallażīna āmanụ wa 'amiluṣ-ṣāliḥāti lahum jannātun tajrī min taḥtihal-an-hār, żālikal-fauzul-kabīr",
            "inna baṭsya rabbika lasyadīd",
            "innahụ huwa yubdi`u wa yu'īd",
            "wa huwal-gafụrul-wadụd",
            "żul-'arsyil-majīd",
            "fa''ālul limā yurīd",
            "hal atāka ḥadīṡul-junụd",
            "fir'auna wa ṡamụd",
            "balillażīna kafarụ fī takżīb",
            "wallāhu miw warā`ihim muḥīṭ",
            "bal huwa qur`ānum majīd",
            "fī lauḥim maḥfụẓ",
    };

    public static String [] ArtiAlBuruj = {"Demi langit yang mempunyai gugusan bintang,",
            "dan demi hari yang dijanjikan.",
            "Demi yang menyaksikan dan yang disaksikan.",
            "Binasalah orang-orang yang membuat parit (yaitu para pembesar Najran di Yaman),",
            "yang berapi (yang mempunyai) kayu bakar,",
            "ketika mereka duduk di sekitarnya,",
            "sedang mereka menyaksikan apa yang mereka perbuat terhadap orang-orang mukmin.",
            "Dan mereka menyiksa orang-orang mukmin itu hanya karena (orang-orang mukmin itu) beriman kepada Allah Yang Mahaperkasa, Maha Terpuji,",
            "yang memiliki kerajaan langit dan bumi. Dan Allah Maha Menyaksikan segala sesuatu.",
            "Sungguh, orang-orang yang mendatangkan cobaan (bencana, membunuh, menyiksa) kepada orang-orang mukmin laki-laki dan perempuan lalu mereka tidak bertobat, maka mereka akan mendapat azab Jahanam dan mereka akan mendapat azab (neraka) yang membakar.",
            "Sungguh, orang-orang yang beriman dan mengerjakan kebajikan, mereka akan mendapat surga yang mengalir di bawahnya sungai-sungai, itulah kemenangan yang agung.",
            "Sungguh, azab Tuhanmu sangat keras.",
            "Sungguh, Dialah yang memulai pen-ciptaan (makhluk) dan yang menghidupkannya (kembali).",
            "Dan Dialah Yang Maha Pengampun, Maha Pengasih,",
            "yang memiliki ‘Arsy, lagi Mahamulia,",
            "Mahakuasa berbuat apa yang Dia kehendaki.",
            "Sudahkah sampai kepadamu berita tentang bala tentara (penentang),",
            "(yaitu) Fir‘aun dan Samud?",
            "Memang orang-orang kafir (selalu) mendustakan,",
            "padahal Allah mengepung dari belakang mereka (sehingga tidak dapat lolos).",
            "Bahkan (yang didustakan itu) ialah Al-Qur'an yang mulia,",
            "yang (tersimpan) dalam (tempat) yang terjaga (Lauh Mahfuzh).",
    };

}
