package com.example.murotalquran.Ayat;

public class AyatAlBalad {

    public static String [] IdAlBalad = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020"
    };

    public static String [] NoAlBalad = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20"
    };

    public static String [] ArabAlBalad = {"لَآ اُقْسِمُ بِهٰذَا الْبَلَدِۙ",
            "وَاَنْتَ حِلٌّۢ بِهٰذَا الْبَلَدِۙ",
            "وَوَالِدٍ وَّمَا وَلَدَۙ",
            "لَقَدْ خَلَقْنَا الْاِنْسَانَ فِيْ كَبَدٍۗ",
            "اَيَحْسَبُ اَنْ لَّنْ يَّقْدِرَ عَلَيْهِ اَحَدٌ ۘ",
            "يَقُوْلُ اَهْلَكْتُ مَالًا لُّبَدًاۗ",
            "اَيَحْسَبُ اَنْ لَّمْ يَرَهٗٓ اَحَدٌۗ",
            "اَلَمْ نَجْعَلْ لَّهٗ عَيْنَيْنِۙ",
            "وَلِسَانًا وَّشَفَتَيْنِۙ",
            "وَهَدَيْنٰهُ النَّجْدَيْنِۙ",
            "فَلَا اقْتَحَمَ الْعَقَبَةَ ۖ",
            "وَمَآ اَدْرٰىكَ مَا الْعَقَبَةُ ۗ",
            "فَكُّ رَقَبَةٍۙ",
            "اَوْ اِطْعَامٌ فِيْ يَوْمٍ ذِيْ مَسْغَبَةٍۙ",
            "يَّتِيْمًا ذَا مَقْرَبَةٍۙ",
            "اَوْ مِسْكِيْنًا ذَا مَتْرَبَةٍۗ",
            "ثُمَّ كَانَ مِنَ الَّذِيْنَ اٰمَنُوْا وَتَوَاصَوْا بِالصَّبْرِ وَتَوَاصَوْا بِالْمَرْحَمَةِۗ",
            "اُولٰۤىِٕكَ اَصْحٰبُ الْمَيْمَنَةِۗ",
            "وَالَّذِيْنَ كَفَرُوْا بِاٰيٰتِنَا هُمْ اَصْحٰبُ الْمَشْئَمَةِۗ",
            "عَلَيْهِمْ نَارٌ مُّؤْصَدَةٌ"
    };

    public static String [] LatinAlBalad = {"lā uqsimu bihāżal-balad",
            "wa anta ḥillum bihāżal-balad",
            "wa wālidiw wa mā walad",
            "laqad khalaqnal-insāna fī kabad",
            "a yaḥsabu al lay yaqdira 'alaihi aḥad",
            "yaqụlu ahlaktu mālal lubadā",
            "a yaḥsabu al lam yarahū aḥad",
            "a lam naj'al lahụ 'ainaīn",
            "wa lisānaw wa syafataīn",
            "wa hadaināhun-najdaīn",
            "fa laqtaḥamal-'aqabah",
            "wa mā adrāka mal-'aqabah",
            "fakku raqabah",
            "au iṭ'āmun fī yaumin żī masgabah",
            "yatīman żā maqrabah",
            "au miskīnan żā matrabah",
            "ṡumma kāna minallażīna āmanụ wa tawāṣau biṣ-ṣabri wa tawāṣau bil-mar-ḥamah",
            "ulā`ika aṣ-ḥābul-maimanah",
            "wallażīna kafarụ bi`āyātinā hum aṣ-ḥābul-masy`amah",
            "'alaihim nārum mu`ṣadah"
    };

    public static String [] ArtiAlBalad = {"Aku bersumpah dengan negeri ini (Mekah),",
            "dan engkau (Muhammad), bertempat di negeri (Mekah) ini,",
            "dan demi (pertalian) bapak dan anaknya.",
            "Sungguh, Kami telah menciptakan manusia berada dalam susah payah.",
            "Apakah dia (manusia) itu mengira bahwa tidak ada sesuatu pun yang berkuasa atasnya?",
            "Dia mengatakan, “Aku telah menghabiskan harta yang banyak.”",
            "Apakah dia mengira bahwa tidak ada sesuatu pun yang melihatnya?",
            "Bukankah Kami telah menjadikan untuknya sepasang mata,",
            "dan lidah dan sepasang bibir?",
            "Dan Kami telah menunjukkan kepadanya dua jalan (kebajikan dan kejahatan),",
            "tetapi dia tidak menempuh jalan yang mendaki dan sukar?",
            "Dan tahukah kamu apakah jalan yang mendaki dan sukar itu?",
            "(yaitu) melepaskan perbudakan (hamba sahaya),",
            "atau memberi makan pada hari terjadi kelaparan,",
            "(kepada) anak yatim yang ada hubungan kerabat,",
            "atau orang miskin yang sangat fakir.",
            "Kemudian dia termasuk orang-orang yang beriman dan saling berpesan untuk bersabar dan saling berpesan untuk berkasih sayang.",
            "Mereka (orang-orang yang beriman dan saling berpesan itu) adalah golongan kanan.",
            "Dan orang-orang yang kafir kepada ayat-ayat Kami, mereka itu adalah golongan kiri.",
            "Mereka berada dalam neraka yang ditutup rapat."
    };

}
