package com.example.murotalquran.Ayat;

public class AyatAlInsyiqaq {

    public static String [] IdAlInsyiqaq = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
            "1023",
            "1024",
            "1025"
    };

    public static String [] NoAlInsyiqaq = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25"
    };

    public static String [] ArabAlInsyiqaq = {"اِذَا السَّمَاۤءُ انْشَقَّتْۙ",
            "وَاَذِنَتْ لِرَبِّهَا وَحُقَّتْۙ",
            "وَاِذَا الْاَرْضُ مُدَّتْۙ",
            "وَاَلْقَتْ مَا فِيْهَا وَتَخَلَّتْۙ",
            "وَاَذِنَتْ لِرَبِّهَا وَحُقَّتْۗ",
            "يٰٓاَيُّهَا الْاِنْسَانُ اِنَّكَ كَادِحٌ اِلٰى رَبِّكَ كَدْحًا فَمُلٰقِيْهِۚ",
            "فَاَمَّا مَنْ اُوْتِيَ كِتٰبَهٗ بِيَمِيْنِهٖۙ",
            "فَسَوْفَ يُحَاسَبُ حِسَابًا يَّسِيْرًاۙ",
            "وَّيَنْقَلِبُ اِلٰٓى اَهْلِهٖ مَسْرُوْرًاۗ",
            "وَاَمَّا مَنْ اُوْتِيَ كِتٰبَهٗ وَرَاۤءَ ظَهْرِهٖۙ",
            "فَسَوْفَ يَدْعُوْ ثُبُوْرًاۙ",
            "وَّيَصْلٰى سَعِيْرًاۗ",
            "اِنَّهٗ كَانَ فِيْٓ اَهْلِهٖ مَسْرُوْرًاۗ",
            "اِنَّهٗ ظَنَّ اَنْ لَّنْ يَّحُوْرَ ۛ",
            "بَلٰىۛ اِنَّ رَبَّهٗ كَانَ بِهٖ بَصِيْرًاۗ",
            "فَلَآ اُقْسِمُ بِالشَّفَقِۙ",
            "وَالَّيْلِ وَمَا وَسَقَۙ",
            "وَالْقَمَرِ اِذَا اتَّسَقَۙ",
            "لَتَرْكَبُنَّ طَبَقًا عَنْ طَبَقٍۗ",
            "فَمَا لَهُمْ لَا يُؤْمِنُوْنَۙ",
            "وَاِذَا قُرِئَ عَلَيْهِمُ الْقُرْاٰنُ لَا يَسْجُدُوْنَ ۗ ۩",
            "بَلِ الَّذِيْنَ كَفَرُوْا يُكَذِّبُوْنَۖ",
            "وَاللّٰهُ اَعْلَمُ بِمَا يُوْعُوْنَۖ",
            "فَبَشِّرْهُمْ بِعَذَابٍ اَلِيْمٍۙ",
            "اِلَّا الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ لَهُمْ اَجْرٌ غَيْرُ مَمْنُوْنٍ"
    };

    public static String [] LatinAlInsyiqaq = {"iżas-samā`unsyaqqat",
            "wa ażinat lirabbihā wa ḥuqqat",
            "wa iżal-arḍu muddat",
            "wa alqat mā fīhā wa takhallat",
            "wa ażinat lirabbihā wa ḥuqqat",
            "yā ayyuhal-insānu innaka kādiḥun ilā rabbika kad-ḥan fa mulāqīh",
            "fa ammā man ụtiya kitābahụ biyamīnih",
            "fa saufa yuḥāsabu ḥisābay yasīrā",
            "wa yangqalibu ilā ahlihī masrụrā",
            "wa ammā man ụtiya kitābahụ warā`a ẓahrih",
            "fa saufa yad'ụ ṡubụrā",
            "wa yaṣlā sa'īrā",
            "innahụ kāna fī ahlihī masrụrā",
            "innahụ ẓanna al lay yaḥụr",
            "balā inna rabbahụ kāna bihī baṣīrā",
            "fa lā uqsimu bisy-syafaq",
            "wal-laili wa mā wasaq",
            "wal-qamari iżattasaq",
            "latarkabunna ṭabaqan 'an ṭabaq",
            "fa mā lahum lā yu`minụn",
            "wa iżā quri`a 'alaihimul-qur`ānu lā yasjudụn",
            "balillażīna kafarụ yukażżibụn",
            "wallāhu a'lamu bimā yụ'ụn",
            "fa basysyir-hum bi'ażābin alīm",
            "illallażīna āmanụ wa 'amiluṣ-ṣāliḥāti lahum ajrun gairu mamnụn"
    };

    public static String [] ArtiAlInsyiqaq = {"Apabila langit terbelah,",
            "dan patuh kepada Tuhannya, dan sudah semestinya patuh,",
            "dan apabila bumi diratakan,",
            "dan memuntahkan apa yang ada di dalamnya dan menjadi kosong,",
            "dan patuh kepada Tuhannya, dan sudah semestinya patuh.",
            "Wahai manusia! Sesungguhnya kamu telah bekerja keras menuju Tuhanmu, maka kamu akan menemui-Nya.",
            "Maka adapun orang yang catatannya diberikan dari sebelah kanannya,",
            "maka dia akan diperiksa dengan pemeriksaan yang mudah,",
            "dan dia akan kembali kepada keluarganya (yang sama-sama beriman) dengan gembira.",
            "Dan adapun orang yang catatannya diberikan dari sebelah belakang,",
            "maka dia akan berteriak, “Celakalah aku!”",
            "Dan dia akan masuk ke dalam api yang menyala-nyala (neraka).",
            "Sungguh, dia dahulu (di dunia) bergembira di kalangan keluarganya (yang sama-sama kafir).",
            "Sesungguhnya dia mengira bahwa dia tidak akan kembali (kepada Tuhannya).",
            "Tidak demikian, sesungguhnya Tuhannya selalu melihatnya.",
            "Maka Aku bersumpah demi cahaya merah pada waktu senja,",
            "demi malam dan apa yang diselubunginya,",
            "demi bulan apabila jadi purnama,",
            "sungguh, akan kamu jalani tingkat demi tingkat (dalam kehidupan).",
            "Maka mengapa mereka tidak mau beriman?",
            "Dan apabila Al-Qur'an dibacakan kepada mereka, mereka tidak (mau) bersujud,",
            "bahkan orang-orang kafir itu mendustakan(nya).",
            "Dan Allah lebih mengetahui apa yang mereka sembunyikan (dalam hati mereka).",
            "Maka sampaikanlah kepada mereka (ancaman) azab yang pedih,",
            "kecuali orang-orang yang beriman dan mengerjakan kebajikan, mereka akan mendapat pahala yang tidak putus-putusnya."
    };

}
