package com.example.murotalquran.Ayat;

public class AyatAlMutaffifin {

    public static String [] IdAlMutaffifin = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
            "1023",
            "1024",
            "1025",
            "1026",
            "1027",
            "1028",
            "1029",
            "1030",
            "1031",
            "1032",
            "1033",
            "1034",
            "1035",
            "1036"
    };

    public static String [] NoAlMutaffifin = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36"
    };

    public static String [] ArabAlMutaffifin = {"وَيْلٌ لِّلْمُطَفِّفِيْنَۙ",
            "الَّذِيْنَ اِذَا اكْتَالُوْا عَلَى النَّاسِ يَسْتَوْفُوْنَۖ",
            "وَاِذَا كَالُوْهُمْ اَوْ وَّزَنُوْهُمْ يُخْسِرُوْنَۗ",
            "اَلَا يَظُنُّ اُولٰۤىِٕكَ اَنَّهُمْ مَّبْعُوْثُوْنَۙ",
            "لِيَوْمٍ عَظِيْمٍۙ",
            "يَّوْمَ يَقُوْمُ النَّاسُ لِرَبِّ الْعٰلَمِيْنَۗ",
            "كَلَّآ اِنَّ كِتٰبَ الْفُجَّارِ لَفِيْ سِجِّيْنٍۗ",
            "وَمَآ اَدْرٰىكَ مَا سِجِّيْنٌۗ",
            "كِتٰبٌ مَّرْقُوْمٌۗ",
            "وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَۙ",
            "الَّذِيْنَ يُكَذِّبُوْنَ بِيَوْمِ الدِّيْنِۗ",
            "وَمَا يُكَذِّبُ بِهٖٓ اِلَّا كُلُّ مُعْتَدٍ اَثِيْمٍۙ",
            "اِذَا تُتْلٰى عَلَيْهِ اٰيٰتُنَا قَالَ اَسَاطِيْرُ الْاَوَّلِيْنَۗ",
            "كَلَّا بَلْ ۜرَانَ عَلٰى قُلُوْبِهِمْ مَّا كَانُوْا يَكْسِبُوْنَ",
            "كَلَّآ اِنَّهُمْ عَنْ رَّبِّهِمْ يَوْمَىِٕذٍ لَّمَحْجُوْبُوْنَۗ",
            "ثُمَّ اِنَّهُمْ لَصَالُوا الْجَحِيْمِۗ",
            "ثُمَّ يُقَالُ هٰذَا الَّذِيْ كُنْتُمْ بِهٖ تُكَذِّبُوْنَۗ",
            "كَلَّآ اِنَّ كِتٰبَ الْاَبْرَارِ لَفِيْ عِلِّيِّيْنَۗ",
            "وَمَآ اَدْرٰىكَ مَا عِلِّيُّوْنَۗ",
            "كِتٰبٌ مَّرْقُوْمٌۙ",
            "يَّشْهَدُهُ الْمُقَرَّبُوْنَۗ",
            "اِنَّ الْاَبْرَارَ لَفِيْ نَعِيْمٍۙ",
            "عَلَى الْاَرَاۤىِٕكِ يَنْظُرُوْنَۙ",
            "تَعْرِفُ فِيْ وُجُوْهِهِمْ نَضْرَةَ النَّعِيْمِۚ",
            "يُسْقَوْنَ مِنْ رَّحِيْقٍ مَّخْتُوْمٍۙ",
            "خِتٰمُهٗ مِسْكٌ ۗوَفِيْ ذٰلِكَ فَلْيَتَنَافَسِ الْمُتَنَافِسُوْنَۗ",
            "وَمِزَاجُهٗ مِنْ تَسْنِيْمٍۙ",
            "عَيْنًا يَّشْرَبُ بِهَا الْمُقَرَّبُوْنَۗ",
            "اِنَّ الَّذِيْنَ اَجْرَمُوْا كَانُوْا مِنَ الَّذِيْنَ اٰمَنُوْا يَضْحَكُوْنَۖ",
            "وَاِذَا مَرُّوْا بِهِمْ يَتَغَامَزُوْنَۖ",
            "وَاِذَا انْقَلَبُوْٓا اِلٰٓى اَهْلِهِمُ انْقَلَبُوْا فَكِهِيْنَۖ",
            "وَاِذَا رَاَوْهُمْ قَالُوْٓا اِنَّ هٰٓؤُلَاۤءِ لَضَاۤلُّوْنَۙ",
            "وَمَآ اُرْسِلُوْا عَلَيْهِمْ حٰفِظِيْنَۗ",
            "فَالْيَوْمَ الَّذِيْنَ اٰمَنُوْا مِنَ الْكُفَّارِ يَضْحَكُوْنَۙ",
            "عَلَى الْاَرَاۤىِٕكِ يَنْظُرُوْنَۗ",
            "هَلْ ثُوِّبَ الْكُفَّارُ مَا كَانُوْا يَفْعَلُوْنَ"
    };

    public static String [] LatinAlMutaffifin = {"wailul lil-muṭaffifīn",
            "allażīna iżaktālụ 'alan-nāsi yastaufụn",
            "wa iżā kālụhum aw wazanụhum yukhsirụn",
            "alā yaẓunnu ulā`ika annahum mab'ụṡụn",
            "liyaumin 'aẓīm",
            "yauma yaqụmun-nāsu lirabbil-'ālamīn",
            "kallā inna kitābal-fujjāri lafī sijjīn",
            "wa mā adrāka mā sijjīn",
            "kitābum marqụm",
            "wailuy yauma`iżil lil-mukażżibīn",
            "allażīna yukażżibụna biyaumid-dīn",
            "wa mā yukażżibu bihī illā kullu mu'tadin aṡīm",
            "iżā tutlā 'alaihi āyātunā qāla asāṭīrul-awwalīn",
            "kallā bal rāna 'alā qulụbihim mā kānụ yaksibụn",
            "kallā innahum 'ar rabbihim yauma`iżil lamaḥjụbụn",
            "ṡumma innahum laṣālul-jaḥīm",
            "ṡumma yuqālu hāżallażī kuntum bihī tukażżibụn",
            "kallā inna kitābal-abrāri lafī 'illiyyīn",
            "wa mā adrāka mā 'illiyyụn",
            "kitābum marqụm",
            "yasy-haduhul-muqarrabụn",
            "innal-abrāra lafī na'īm",
            "'alal-arā`iki yanẓurụn",
            "ta'rifu fī wujụhihim naḍratan na'īm",
            "yusqauna mir raḥīqim makhtụm",
            "khitāmuhụ misk, wa fī żālika falyatanāfasil-mutanāfisụn",
            "wa mizājuhụ min tasnīm",
            "'ainay yasyrabu bihal-muqarrabụn",
            "innallażīna ajramụ kānụ minallażīna āmanụ yaḍ-ḥakụn",
            "wa iżā marrụ bihim yatagāmazụn",
            "wa iżangqalabū ilā ahlihimungqalabụ fakihīn",
            "wa iżā ra`auhum qālū inna hā`ulā`i laḍāllụn",
            "wa mā ursilụ 'alaihim ḥāfiẓīn",
            "fal-yaumallażīna āmanụ minal-kuffāri yaḍ-ḥakụn",
            "'alal-arā`iki yanẓurụn",
            "hal ṡuwwibal-kuffāru mā kānụ yaf'alụn"
    };

    public static String [] ArtiAlMutaffifin = {"Celakalah bagi orang-orang yang curang (dalam menakar dan menimbang)!",
            "(Yaitu) orang-orang yang apabila menerima takaran dari orang lain mereka minta dicukupkan,",
            "dan apabila mereka menakar atau menimbang (untuk orang lain), mereka mengurangi.",
            "Tidakkah mereka itu mengira, bahwa sesungguhnya mereka akan dibangkitkan,",
            "pada suatu hari yang besar,",
            "(yaitu) pada hari (ketika) semua orang bangkit menghadap Tuhan seluruh alam.",
            "Sekali-kali jangan begitu! Sesungguhnya catatan orang yang durhaka benar-benar tersimpan dalam Sijjin.",
            "Dan tahukah engkau apakah Sijjin itu?",
            "(Yaitu) Kitab yang berisi catatan (amal).",
            "Celakalah pada hari itu, bagi orang-orang yang mendustakan!",
            "(yaitu) orang-orang yang mendustakannya (hari pembalasan).",
            "Dan tidak ada yang mendustakannya (hari pembalasan) kecuali setiap orang yang melampaui batas dan berdosa,",
            "yang apabila dibacakan kepadanya ayat-ayat Kami, dia berkata, “Itu adalah dongeng orang-orang dahulu.”",
            "Sekali-kali tidak! Bahkan apa yang mereka kerjakan itu telah menutupi hati mereka.",
            "Sekali-kali tidak! Sesungguhnya mereka pada hari itu benar-benar terhalang dari (melihat) Tuhannya.",
            "Kemudian, sesungguhnya mereka benar-benar masuk neraka.",
            "Kemudian, dikatakan (kepada mereka), “Inilah (azab) yang dahulu kamu dustakan.”",
            "Sekali-kali tidak! Sesungguhnya catatan orang-orang yang berbakti benar-benar tersimpan dalam ’Illiyyin.",
            "Dan tahukah engkau apakah ’Illiyyin itu?",
            "(Yaitu) Kitab yang berisi catatan (amal),",
            "yang disaksikan oleh (malaikat-malaikat) yang didekatkan (kepada Allah).",
            "Sesungguhnya orang-orang yang berbakti benar-benar berada dalam (surga yang penuh) kenikmatan,",
            "mereka (duduk) di atas dipan-dipan melepas pandangan.",
            "Kamu dapat mengetahui dari wajah mereka kesenangan hidup yang penuh kenikmatan.",
            "Mereka diberi minum dari khamar murni (tidak memabukkan) yang (tempatnya) masih dilak (disegel),",
            "laknya dari kasturi. Dan untuk yang demikian itu hendaknya orang berlomba-lomba.",
            "Dan campurannya dari tasnim,",
            "(yaitu) mata air yang diminum oleh mereka yang dekat (kepada Allah).",
            "Sesungguhnya orang-orang yang berdosa adalah mereka yang dahulu menertawakan orang-orang yang beriman.",
            "Dan apabila mereka (orang-orang yang beriman) melintas di hadapan mereka, mereka saling mengedip-ngedipkan matanya,",
            "dan apabila kembali kepada kaumnya, mereka kembali dengan gembira ria.",
            "Dan apabila mereka melihat (orang-orang mukmin), mereka mengatakan, “Sesungguhnya mereka benar-benar orang-orang sesat,”",
            "padahal (orang-orang yang berdosa itu), mereka tidak diutus sebagai penjaga (orang-orang mukmin).",
            "Maka pada hari ini, orang-orang yang beriman yang menertawakan orang-orang kafir,",
            "mereka (duduk) di atas dipan-dipan melepas pandangan.",
            "Apakah orang-orang kafir itu diberi balasan (hukuman) terhadap apa yang telah mereka perbuat?"
    };

}
