package com.example.murotalquran.Ayat;

public class AyatAlAla {

    public static String [] IdAlAla = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019"
    };

    public static String [] NoAlAla = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19"
    };

    public static String [] ArabAlAla = {"سَبِّحِ اسْمَ رَبِّكَ الْاَعْلَىۙ",
            "الَّذِيْ خَلَقَ فَسَوّٰىۖ",
            "وَالَّذِيْ قَدَّرَ فَهَدٰىۖ",
            "وَالَّذِيْٓ اَخْرَجَ الْمَرْعٰىۖ",
            "فَجَعَلَهٗ غُثَاۤءً اَحْوٰىۖ",
            "سَنُقْرِئُكَ فَلَا تَنْسٰىٓ ۖ",
            "اِلَّا مَا شَاۤءَ اللّٰهُ ۗاِنَّهٗ يَعْلَمُ الْجَهْرَ وَمَا يَخْفٰىۗ",
            "وَنُيَسِّرُكَ لِلْيُسْرٰىۖ",
            "فَذَكِّرْ اِنْ نَّفَعَتِ الذِّكْرٰىۗ",
            "سَيَذَّكَّرُ مَنْ يَّخْشٰىۙ",
            "وَيَتَجَنَّبُهَا الْاَشْقَىۙ",
            "الَّذِيْ يَصْلَى النَّارَ الْكُبْرٰىۚ",
            "ثُمَّ لَا يَمُوْتُ فِيْهَا وَلَا يَحْيٰىۗ",
            "قَدْ اَفْلَحَ مَنْ تَزَكّٰىۙ",
            "وَذَكَرَ اسْمَ رَبِّهٖ فَصَلّٰىۗ",
            "بَلْ تُؤْثِرُوْنَ الْحَيٰوةَ الدُّنْيَاۖ",
            "وَالْاٰخِرَةُ خَيْرٌ وَّاَبْقٰىۗ",
            "اِنَّ هٰذَا لَفِى الصُّحُفِ الْاُوْلٰىۙ",
            "صُحُفِ اِبْرٰهِيْمَ وَمُوْسٰى"
    };

    public static String [] LatinAlAla = {"sabbiḥisma rabbikal-a'lā",
            "allażī khalaqa fa sawwā",
            "wallażī qaddara fa hadā",
            "wallażī akhrajal-mar'ā",
            "fa ja'alahụ guṡā`an aḥwā",
            "sanuqri`uka fa lā tansā",
            "illā mā syā`allāh, innahụ ya'lamul-jahra wa mā yakhfā",
            "wa nuyassiruka lil-yusrā",
            "fa żakkir in nafa'atiż-żikrā",
            "sayażżakkaru may yakhsyā",
            "wa yatajannabuhal-asyqā",
            "allażī yaṣlan-nāral-kubrā",
            "ṡumma lā yamụtu fīhā wa lā yaḥyā",
            "qad aflaḥa man tazakkā",
            "wa żakarasma rabbihī fa ṣallā",
            "bal tu`ṡirụnal-ḥayātad-dun-yā",
            "wal-ākhiratu khairuw wa abqā",
            "inna hāżā lafiṣ-ṣuḥufil-ụlā",
            "ṣuḥufi ibrāhīma wa mụsā"
    };

    public static String [] ArtiAlAla = {"Sucikanlah nama Tuhanmu Yang Mahatinggi,",
            "Yang menciptakan, lalu menyempurnakan (ciptaan-Nya).",
            "Yang menentukan kadar (masing-masing) dan memberi petunjuk,",
            "dan Yang menumbuhkan rerumputan,",
            "lalu dijadikan-Nya (rumput-rumput) itu kering kehitam-hitaman.",
            "Kami akan membacakan (Al-Qur'an) kepadamu (Muhammad) sehingga engkau tidak akan lupa,",
            "kecuali jika Allah menghendaki. Sungguh, Dia mengetahui yang terang dan yang tersembunyi.",
            "Dan Kami akan memudahkan bagimu ke jalan kemudahan (mencapai kebahagiaan dunia dan akhirat),",
            "oleh sebab itu berikanlah peringatan, karena peringatan itu bermanfaat,",
            "orang yang takut (kepada Allah) akan mendapat pelajaran,",
            "dan orang-orang yang celaka (kafir) akan menjauhinya,",
            "(yaitu) orang yang akan memasuki api yang besar (neraka),",
            "selanjutnya dia di sana tidak mati dan tidak (pula) hidup.",
            "Sungguh beruntung orang yang menyucikan diri (dengan beriman),",
            "dan mengingat nama Tuhannya, lalu dia salat.",
            "Sedangkan kamu (orang-orang kafir) memilih kehidupan dunia,",
            "padahal kehidupan akhirat itu lebih baik dan lebih kekal.",
            "Sesungguhnya ini terdapat dalam kitab-kitab yang dahulu,",
            "(yaitu) kitab-kitab Ibrahim dan Musa."
    };

}
