package com.example.murotalquran.Ayat;

public class AyatAtTakwir {

    public static String [] IdAtTakwir = {"1001",
            "1002",
            "1003",
            "1004",
            "1005",
            "1006",
            "1007",
            "1008",
            "1009",
            "1010",
            "1011",
            "1012",
            "1013",
            "1014",
            "1015",
            "1016",
            "1017",
            "1018",
            "1019",
            "1020",
            "1021",
            "1022",
            "1023",
            "1024",
            "1025",
            "1026",
            "1027",
            "1028",
            "1029"
    };

    public static String [] NoAtTakwir = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29"
    };

    public static String [] ArabAtTakwir = {"اِذَا الشَّمْسُ كُوِّرَتْۖ",
            "وَاِذَا النُّجُوْمُ انْكَدَرَتْۖ",
            "وَاِذَا الْجِبَالُ سُيِّرَتْۖ",
            "وَاِذَا الْعِشَارُ عُطِّلَتْۖ",
            "وَاِذَا الْوُحُوْشُ حُشِرَتْۖ",
            "وَاِذَا الْبِحَارُ سُجِّرَتْۖ",
            "وَاِذَا النُّفُوْسُ زُوِّجَتْۖ",
            "وَاِذَا الْمَوْءٗدَةُ سُىِٕلَتْۖ",
            "بِاَيِّ ذَنْۢبٍ قُتِلَتْۚ",
            "وَاِذَا الصُّحُفُ نُشِرَتْۖ",
            "وَاِذَا السَّمَاۤءُ كُشِطَتْۖ",
            "وَاِذَا الْجَحِيْمُ سُعِّرَتْۖ",
            "وَاِذَا الْجَنَّةُ اُزْلِفَتْۖ",
            "عَلِمَتْ نَفْسٌ مَّآ اَحْضَرَتْۗ",
            "فَلَآ اُقْسِمُ بِالْخُنَّسِۙ",
            "الْجَوَارِ الْكُنَّسِۙ",
            "وَالَّيْلِ اِذَا عَسْعَسَۙ",
            "وَالصُّبْحِ اِذَا تَنَفَّسَۙ",
            "اِنَّهٗ لَقَوْلُ رَسُوْلٍ كَرِيْمٍۙ",
            "ذِيْ قُوَّةٍ عِنْدَ ذِى الْعَرْشِ مَكِيْنٍۙ",
            "مُّطَاعٍ ثَمَّ اَمِيْنٍۗ",
            "وَمَا صَاحِبُكُمْ بِمَجْنُوْنٍۚ",
            "وَلَقَدْ رَاٰهُ بِالْاُفُقِ الْمُبِيْنِۚ",
            "وَمَا هُوَ عَلَى الْغَيْبِ بِضَنِيْنٍۚ",
            "وَمَا هُوَ بِقَوْلِ شَيْطٰنٍ رَّجِيْمٍٍۚۚ",
            "فَاَيْنَ تَذْهَبُوْنَۗ",
            "اِنْ هُوَ اِلَّا ذِكْرٌ لِّلْعٰلَمِيْنَۙ",
            "لِمَنْ شَاۤءَ مِنْكُمْ اَنْ يَّسْتَقِيْمَۗ",
            "وَمَا تَشَاۤءُوْنَ اِلَّآ اَنْ يَّشَاۤءَ اللّٰهُ رَبُّ الْعٰلَمِيْنَ"
    };

    public static String [] LatinAtTakwir = {"iżasy-syamsu kuwwirat",
            "wa iżan-nujụmungkadarat",
            "wa iżal-jibālu suyyirat",
            "wa iżal-'isyāru 'uṭṭilat",
            "wa iżal-wuḥụsyu ḥusyirat",
            "wa iżal-biḥāru sujjirat",
            "wa iżan-nufụsu zuwwijat",
            "wa iżal-mau`ụdatu su`ilat",
            "bi`ayyi żambing qutilat",
            "wa iżaṣ-ṣuḥufu nusyirat",
            "wa iżas-samā`u kusyiṭat",
            "wa iżal-jaḥīmu su''irat",
            "wa iżal-jannatu uzlifat",
            "'alimat nafsum mā aḥḍarat",
            "fa lā uqsimu bil-khunnas",
            "al-jawāril-kunnas",
            "wal-laili iżā 'as'as",
            "waṣ-ṣub-ḥi iżā tanaffas",
            "innahụ laqaulu rasụling karīm",
            "żī quwwatin 'inda żil-'arsyi makīn",
            "muṭā'in ṡamma amīn",
            "wa mā ṣāḥibukum bimajnụn",
            "wa laqad ra`āhu bil-ufuqil-mubīn",
            "wa mā huwa 'alal-gaibi biḍanīn",
            "wa mā huwa biqauli syaiṭānir rajīm",
            "fa aina taż-habụn",
            "in huwa illā żikrul lil-'ālamīn",
            "liman syā`a mingkum ay yastaqīm",
            "wa mā tasyā`ụna illā ay yasyā`allāhu rabbul-'ālamīn"
    };

    public static String [] ArtiAtTakwir = {"Apabila matahari digulung,",
            "dan apabila bintang-bintang berjatuhan,",
            "dan apabila gunung-gunung dihancurkan,",
            "dan apabila unta-unta yang bunting ditinggalkan (tidak terurus),",
            "dan apabila binatang-binatang liar dikumpulkan,",
            "dan apabila lautan dipanaskan,",
            "dan apabila roh-roh dipertemukan (dengan tubuh),",
            "dan apabila bayi-bayi perempuan yang dikubur hidup-hidup ditanya,",
            "karena dosa apa dia dibunuh?",
            "Dan apabila lembaran-lembaran (catatan amal) telah dibuka lebar-lebar,",
            "dan apabila langit dilenyapkan,",
            "dan apabila neraka Jahim dinyalakan,",
            "dan apabila surga didekatkan,",
            "setiap jiwa akan mengetahui apa yang telah dikerjakannya.",
            "Aku bersumpah demi bintang-bintang,",
            "yang beredar dan terbenam,",
            "demi malam apabila telah larut,",
            "dan demi subuh apabila fajar telah menyingsing,",
            "sesungguhnya (Al-Qur'an) itu benar-benar firman (Allah yang dibawa oleh) utusan yang mulia (Jibril),",
            "yang memiliki kekuatan, memiliki kedudukan tinggi di sisi (Allah) yang memiliki ‘Arsy,",
            "yang di sana (di alam malaikat) ditaati dan dipercaya.",
            "Dan temanmu (Muhammad) itu bukanlah orang gila.",
            "Dan sungguh, dia (Muhammad) telah melihatnya (Jibril) di ufuk yang terang.",
            "Dan dia (Muhammad) bukanlah seorang yang kikir (enggan) untuk menerangkan yang gaib.",
            "Dan (Al-Qur'an) itu bukanlah perkataan setan yang terkutuk,",
            "maka ke manakah kamu akan pergi?",
            "(Al-Qur'an) itu tidak lain adalah peringatan bagi seluruh alam,",
            "(yaitu) bagi siapa di antara kamu yang menghendaki menempuh jalan yang lurus.",
            "Dan kamu tidak dapat menghendaki (menempuh jalan itu) kecuali apabila dikehendaki Allah, Tuhan seluruh alam."

    };

}

